/* tslint:disable */
/* eslint-disable */
/**
 * RAG API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Agent,
  AgentInfo,
  GenericException,
  HTTPValidationError,
} from '../models/index';
import {
    AgentFromJSON,
    AgentToJSON,
    AgentInfoFromJSON,
    AgentInfoToJSON,
    GenericExceptionFromJSON,
    GenericExceptionToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/index';

export interface AddAgentApiV1AgentsPostRequest {
    agentInfo: AgentInfo;
}

export interface DeleteAgentApiV1AgentsAgentIdDeleteRequest {
    agentId: string;
}

export interface UpdateAgentApiV1AgentsAgentIdPatchRequest {
    agentId: string;
    agentInfo: AgentInfo;
}

/**
 * 
 */
export class AgentsApi extends runtime.BaseAPI {

    /**
     * Create a new agent.
     * Add Agent
     */
    async addAgentApiV1AgentsPostRaw(requestParameters: AddAgentApiV1AgentsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Agent>> {
        if (requestParameters['agentInfo'] == null) {
            throw new runtime.RequiredError(
                'agentInfo',
                'Required parameter "agentInfo" was null or undefined when calling addAgentApiV1AgentsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/agents/`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AgentInfoToJSON(requestParameters['agentInfo']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AgentFromJSON(jsonValue));
    }

    /**
     * Create a new agent.
     * Add Agent
     */
    async addAgentApiV1AgentsPost(requestParameters: AddAgentApiV1AgentsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Agent> {
        const response = await this.addAgentApiV1AgentsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete an agent by ID.
     * Delete Agent
     */
    async deleteAgentApiV1AgentsAgentIdDeleteRaw(requestParameters: DeleteAgentApiV1AgentsAgentIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['agentId'] == null) {
            throw new runtime.RequiredError(
                'agentId',
                'Required parameter "agentId" was null or undefined when calling deleteAgentApiV1AgentsAgentIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/agents/{agent_id}`;
        urlPath = urlPath.replace(`{${"agent_id"}}`, encodeURIComponent(String(requestParameters['agentId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Delete an agent by ID.
     * Delete Agent
     */
    async deleteAgentApiV1AgentsAgentIdDelete(requestParameters: DeleteAgentApiV1AgentsAgentIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.deleteAgentApiV1AgentsAgentIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List agents accessible to the current user.
     * List Agents Accessible
     */
    async listAgentsAccessibleApiV1AgentsAccessibleGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Agent>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/agents/accessible`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(AgentFromJSON));
    }

    /**
     * List agents accessible to the current user.
     * List Agents Accessible
     */
    async listAgentsAccessibleApiV1AgentsAccessibleGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Agent>> {
        const response = await this.listAgentsAccessibleApiV1AgentsAccessibleGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * List agents created by the current user.
     * List Agents Created
     */
    async listAgentsCreatedApiV1AgentsCreatedGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Agent>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/agents/created`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(AgentFromJSON));
    }

    /**
     * List agents created by the current user.
     * List Agents Created
     */
    async listAgentsCreatedApiV1AgentsCreatedGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Agent>> {
        const response = await this.listAgentsCreatedApiV1AgentsCreatedGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Update an agent by ID.
     * Update Agent
     */
    async updateAgentApiV1AgentsAgentIdPatchRaw(requestParameters: UpdateAgentApiV1AgentsAgentIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Agent>> {
        if (requestParameters['agentId'] == null) {
            throw new runtime.RequiredError(
                'agentId',
                'Required parameter "agentId" was null or undefined when calling updateAgentApiV1AgentsAgentIdPatch().'
            );
        }

        if (requestParameters['agentInfo'] == null) {
            throw new runtime.RequiredError(
                'agentInfo',
                'Required parameter "agentInfo" was null or undefined when calling updateAgentApiV1AgentsAgentIdPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/agents/{agent_id}`;
        urlPath = urlPath.replace(`{${"agent_id"}}`, encodeURIComponent(String(requestParameters['agentId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: AgentInfoToJSON(requestParameters['agentInfo']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AgentFromJSON(jsonValue));
    }

    /**
     * Update an agent by ID.
     * Update Agent
     */
    async updateAgentApiV1AgentsAgentIdPatch(requestParameters: UpdateAgentApiV1AgentsAgentIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Agent> {
        const response = await this.updateAgentApiV1AgentsAgentIdPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
