/* tslint:disable */
/* eslint-disable */
/**
 * RAG API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AgentCreate,
  AgentResponse,
  AgentUpdate,
  AgentUsersAndCreatorsResponse,
  BodyUpdateAgentUsersAndCreatorsApiV1AgentsAgentIdUsersPost,
  GenericException,
  HTTPValidationError,
} from '../models/index';
import {
    AgentCreateFromJSON,
    AgentCreateToJSON,
    AgentResponseFromJSON,
    AgentResponseToJSON,
    AgentUpdateFromJSON,
    AgentUpdateToJSON,
    AgentUsersAndCreatorsResponseFromJSON,
    AgentUsersAndCreatorsResponseToJSON,
    BodyUpdateAgentUsersAndCreatorsApiV1AgentsAgentIdUsersPostFromJSON,
    BodyUpdateAgentUsersAndCreatorsApiV1AgentsAgentIdUsersPostToJSON,
    GenericExceptionFromJSON,
    GenericExceptionToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/index';

export interface AddAgentApiV1AgentsPostRequest {
    agentCreate: AgentCreate;
}

export interface DeleteAgentApiV1AgentsAgentIdDeleteRequest {
    agentId: string;
}

export interface GetAgentSettingsApiV1AgentsSettingsAgentIdGetRequest {
    agentId: string;
}

export interface GetAgentUsersAndCreatorsApiV1AgentsAgentIdUsersGetRequest {
    agentId: string;
}

export interface GetCurrentAgentSettingsApiV1AgentsSettingsAgentIdCurrentGetRequest {
    agentId: string;
}

export interface GetIndexSettingsApiV1AgentsSettingsAgentIdIndexGetRequest {
    agentId: string;
}

export interface GetReasoningSettingsApiV1AgentsSettingsAgentIdReasoningGetRequest {
    agentId: string;
}

export interface UpdateAgentApiV1AgentsAgentIdPatchRequest {
    agentId: string;
    agentUpdate: AgentUpdate;
}

export interface UpdateAgentSettingsApiV1AgentsSettingsAgentIdPatchRequest {
    agentId: string;
    requestBody: { [key: string]: any; };
}

export interface UpdateAgentUsersAndCreatorsApiV1AgentsAgentIdUsersPostRequest {
    agentId: string;
    bodyUpdateAgentUsersAndCreatorsApiV1AgentsAgentIdUsersPost: BodyUpdateAgentUsersAndCreatorsApiV1AgentsAgentIdUsersPost;
}

/**
 * 
 */
export class AgentsApi extends runtime.BaseAPI {

    /**
     * Create a new agent.
     * Add Agent
     */
    async addAgentApiV1AgentsPostRaw(requestParameters: AddAgentApiV1AgentsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AgentResponse>> {
        if (requestParameters['agentCreate'] == null) {
            throw new runtime.RequiredError(
                'agentCreate',
                'Required parameter "agentCreate" was null or undefined when calling addAgentApiV1AgentsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/agents/`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AgentCreateToJSON(requestParameters['agentCreate']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AgentResponseFromJSON(jsonValue));
    }

    /**
     * Create a new agent.
     * Add Agent
     */
    async addAgentApiV1AgentsPost(requestParameters: AddAgentApiV1AgentsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AgentResponse> {
        const response = await this.addAgentApiV1AgentsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete an agent by ID.
     * Delete Agent
     */
    async deleteAgentApiV1AgentsAgentIdDeleteRaw(requestParameters: DeleteAgentApiV1AgentsAgentIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['agentId'] == null) {
            throw new runtime.RequiredError(
                'agentId',
                'Required parameter "agentId" was null or undefined when calling deleteAgentApiV1AgentsAgentIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/agents/{agent_id}`;
        urlPath = urlPath.replace(`{${"agent_id"}}`, encodeURIComponent(String(requestParameters['agentId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Delete an agent by ID.
     * Delete Agent
     */
    async deleteAgentApiV1AgentsAgentIdDelete(requestParameters: DeleteAgentApiV1AgentsAgentIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.deleteAgentApiV1AgentsAgentIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get settings for an agent by ID.
     * Get Agent Settings
     */
    async getAgentSettingsApiV1AgentsSettingsAgentIdGetRaw(requestParameters: GetAgentSettingsApiV1AgentsSettingsAgentIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        if (requestParameters['agentId'] == null) {
            throw new runtime.RequiredError(
                'agentId',
                'Required parameter "agentId" was null or undefined when calling getAgentSettingsApiV1AgentsSettingsAgentIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/agents/settings/{agent_id}`;
        urlPath = urlPath.replace(`{${"agent_id"}}`, encodeURIComponent(String(requestParameters['agentId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Get settings for an agent by ID.
     * Get Agent Settings
     */
    async getAgentSettingsApiV1AgentsSettingsAgentIdGet(requestParameters: GetAgentSettingsApiV1AgentsSettingsAgentIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.getAgentSettingsApiV1AgentsSettingsAgentIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get users and creators for an agent by ID.
     * Get Agent Users And Creators
     */
    async getAgentUsersAndCreatorsApiV1AgentsAgentIdUsersGetRaw(requestParameters: GetAgentUsersAndCreatorsApiV1AgentsAgentIdUsersGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AgentUsersAndCreatorsResponse>> {
        if (requestParameters['agentId'] == null) {
            throw new runtime.RequiredError(
                'agentId',
                'Required parameter "agentId" was null or undefined when calling getAgentUsersAndCreatorsApiV1AgentsAgentIdUsersGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/agents/{agent_id}/users`;
        urlPath = urlPath.replace(`{${"agent_id"}}`, encodeURIComponent(String(requestParameters['agentId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AgentUsersAndCreatorsResponseFromJSON(jsonValue));
    }

    /**
     * Get users and creators for an agent by ID.
     * Get Agent Users And Creators
     */
    async getAgentUsersAndCreatorsApiV1AgentsAgentIdUsersGet(requestParameters: GetAgentUsersAndCreatorsApiV1AgentsAgentIdUsersGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AgentUsersAndCreatorsResponse> {
        const response = await this.getAgentUsersAndCreatorsApiV1AgentsAgentIdUsersGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get current settings for an agent by ID.
     * Get Current Agent Settings
     */
    async getCurrentAgentSettingsApiV1AgentsSettingsAgentIdCurrentGetRaw(requestParameters: GetCurrentAgentSettingsApiV1AgentsSettingsAgentIdCurrentGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        if (requestParameters['agentId'] == null) {
            throw new runtime.RequiredError(
                'agentId',
                'Required parameter "agentId" was null or undefined when calling getCurrentAgentSettingsApiV1AgentsSettingsAgentIdCurrentGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/agents/settings/{agent_id}/current`;
        urlPath = urlPath.replace(`{${"agent_id"}}`, encodeURIComponent(String(requestParameters['agentId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Get current settings for an agent by ID.
     * Get Current Agent Settings
     */
    async getCurrentAgentSettingsApiV1AgentsSettingsAgentIdCurrentGet(requestParameters: GetCurrentAgentSettingsApiV1AgentsSettingsAgentIdCurrentGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.getCurrentAgentSettingsApiV1AgentsSettingsAgentIdCurrentGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get index settings for an agent by ID.
     * Get Index Settings
     */
    async getIndexSettingsApiV1AgentsSettingsAgentIdIndexGetRaw(requestParameters: GetIndexSettingsApiV1AgentsSettingsAgentIdIndexGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        if (requestParameters['agentId'] == null) {
            throw new runtime.RequiredError(
                'agentId',
                'Required parameter "agentId" was null or undefined when calling getIndexSettingsApiV1AgentsSettingsAgentIdIndexGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/agents/settings/{agent_id}/index`;
        urlPath = urlPath.replace(`{${"agent_id"}}`, encodeURIComponent(String(requestParameters['agentId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Get index settings for an agent by ID.
     * Get Index Settings
     */
    async getIndexSettingsApiV1AgentsSettingsAgentIdIndexGet(requestParameters: GetIndexSettingsApiV1AgentsSettingsAgentIdIndexGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.getIndexSettingsApiV1AgentsSettingsAgentIdIndexGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get reasoning settings for an agent by ID.
     * Get Reasoning Settings
     */
    async getReasoningSettingsApiV1AgentsSettingsAgentIdReasoningGetRaw(requestParameters: GetReasoningSettingsApiV1AgentsSettingsAgentIdReasoningGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        if (requestParameters['agentId'] == null) {
            throw new runtime.RequiredError(
                'agentId',
                'Required parameter "agentId" was null or undefined when calling getReasoningSettingsApiV1AgentsSettingsAgentIdReasoningGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/agents/settings/{agent_id}/reasoning`;
        urlPath = urlPath.replace(`{${"agent_id"}}`, encodeURIComponent(String(requestParameters['agentId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Get reasoning settings for an agent by ID.
     * Get Reasoning Settings
     */
    async getReasoningSettingsApiV1AgentsSettingsAgentIdReasoningGet(requestParameters: GetReasoningSettingsApiV1AgentsSettingsAgentIdReasoningGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.getReasoningSettingsApiV1AgentsSettingsAgentIdReasoningGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List agents accessible to the current user.
     * List Agents Accessible
     */
    async listAgentsAccessibleApiV1AgentsAccessibleGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<AgentResponse>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/agents/accessible`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(AgentResponseFromJSON));
    }

    /**
     * List agents accessible to the current user.
     * List Agents Accessible
     */
    async listAgentsAccessibleApiV1AgentsAccessibleGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<AgentResponse>> {
        const response = await this.listAgentsAccessibleApiV1AgentsAccessibleGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * List agents created by the current user.
     * List Agents Created
     */
    async listAgentsCreatedApiV1AgentsCreatedGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<AgentResponse>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/agents/created`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(AgentResponseFromJSON));
    }

    /**
     * List agents created by the current user.
     * List Agents Created
     */
    async listAgentsCreatedApiV1AgentsCreatedGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<AgentResponse>> {
        const response = await this.listAgentsCreatedApiV1AgentsCreatedGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Update an agent by ID.
     * Update Agent
     */
    async updateAgentApiV1AgentsAgentIdPatchRaw(requestParameters: UpdateAgentApiV1AgentsAgentIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AgentResponse>> {
        if (requestParameters['agentId'] == null) {
            throw new runtime.RequiredError(
                'agentId',
                'Required parameter "agentId" was null or undefined when calling updateAgentApiV1AgentsAgentIdPatch().'
            );
        }

        if (requestParameters['agentUpdate'] == null) {
            throw new runtime.RequiredError(
                'agentUpdate',
                'Required parameter "agentUpdate" was null or undefined when calling updateAgentApiV1AgentsAgentIdPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/agents/{agent_id}`;
        urlPath = urlPath.replace(`{${"agent_id"}}`, encodeURIComponent(String(requestParameters['agentId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: AgentUpdateToJSON(requestParameters['agentUpdate']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AgentResponseFromJSON(jsonValue));
    }

    /**
     * Update an agent by ID.
     * Update Agent
     */
    async updateAgentApiV1AgentsAgentIdPatch(requestParameters: UpdateAgentApiV1AgentsAgentIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AgentResponse> {
        const response = await this.updateAgentApiV1AgentsAgentIdPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update settings for an agent by ID.
     * Update Agent Settings
     */
    async updateAgentSettingsApiV1AgentsSettingsAgentIdPatchRaw(requestParameters: UpdateAgentSettingsApiV1AgentsSettingsAgentIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['agentId'] == null) {
            throw new runtime.RequiredError(
                'agentId',
                'Required parameter "agentId" was null or undefined when calling updateAgentSettingsApiV1AgentsSettingsAgentIdPatch().'
            );
        }

        if (requestParameters['requestBody'] == null) {
            throw new runtime.RequiredError(
                'requestBody',
                'Required parameter "requestBody" was null or undefined when calling updateAgentSettingsApiV1AgentsSettingsAgentIdPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/agents/settings/{agent_id}`;
        urlPath = urlPath.replace(`{${"agent_id"}}`, encodeURIComponent(String(requestParameters['agentId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['requestBody'],
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Update settings for an agent by ID.
     * Update Agent Settings
     */
    async updateAgentSettingsApiV1AgentsSettingsAgentIdPatch(requestParameters: UpdateAgentSettingsApiV1AgentsSettingsAgentIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.updateAgentSettingsApiV1AgentsSettingsAgentIdPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update users and creators for an agent by ID.
     * Update Agent Users And Creators
     */
    async updateAgentUsersAndCreatorsApiV1AgentsAgentIdUsersPostRaw(requestParameters: UpdateAgentUsersAndCreatorsApiV1AgentsAgentIdUsersPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['agentId'] == null) {
            throw new runtime.RequiredError(
                'agentId',
                'Required parameter "agentId" was null or undefined when calling updateAgentUsersAndCreatorsApiV1AgentsAgentIdUsersPost().'
            );
        }

        if (requestParameters['bodyUpdateAgentUsersAndCreatorsApiV1AgentsAgentIdUsersPost'] == null) {
            throw new runtime.RequiredError(
                'bodyUpdateAgentUsersAndCreatorsApiV1AgentsAgentIdUsersPost',
                'Required parameter "bodyUpdateAgentUsersAndCreatorsApiV1AgentsAgentIdUsersPost" was null or undefined when calling updateAgentUsersAndCreatorsApiV1AgentsAgentIdUsersPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/agents/{agent_id}/users`;
        urlPath = urlPath.replace(`{${"agent_id"}}`, encodeURIComponent(String(requestParameters['agentId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BodyUpdateAgentUsersAndCreatorsApiV1AgentsAgentIdUsersPostToJSON(requestParameters['bodyUpdateAgentUsersAndCreatorsApiV1AgentsAgentIdUsersPost']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Update users and creators for an agent by ID.
     * Update Agent Users And Creators
     */
    async updateAgentUsersAndCreatorsApiV1AgentsAgentIdUsersPost(requestParameters: UpdateAgentUsersAndCreatorsApiV1AgentsAgentIdUsersPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.updateAgentUsersAndCreatorsApiV1AgentsAgentIdUsersPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
