/* tslint:disable */
/* eslint-disable */
/**
 * RAG API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ChatRequest,
  GenericException,
  HTTPValidationError,
  Liked,
} from '../models/index';
import {
    ChatRequestFromJSON,
    ChatRequestToJSON,
    GenericExceptionFromJSON,
    GenericExceptionToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    LikedFromJSON,
    LikedToJSON,
} from '../models/index';

export interface ChatWithAgentApiV1ChatAgentIdConversationIdPostRequest {
    agentId: string;
    conversationId: string;
    chatRequest: ChatRequest;
}

export interface LikeMessageApiV1ChatAgentIdConversationIdLikePostRequest {
    agentId: string;
    conversationId: string;
    messageIndex: number;
    liked?: Liked;
}

export interface SelectConversationApiV1ChatAgentIdConversationIdSelectPostRequest {
    agentId: string;
    conversationId: string;
}

/**
 * 
 */
export class ChatApi extends runtime.BaseAPI {

    /**
     * Send a message to an agent within a specific conversation.
     * Chat With Agent
     */
    async chatWithAgentApiV1ChatAgentIdConversationIdPostRaw(requestParameters: ChatWithAgentApiV1ChatAgentIdConversationIdPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['agentId'] == null) {
            throw new runtime.RequiredError(
                'agentId',
                'Required parameter "agentId" was null or undefined when calling chatWithAgentApiV1ChatAgentIdConversationIdPost().'
            );
        }

        if (requestParameters['conversationId'] == null) {
            throw new runtime.RequiredError(
                'conversationId',
                'Required parameter "conversationId" was null or undefined when calling chatWithAgentApiV1ChatAgentIdConversationIdPost().'
            );
        }

        if (requestParameters['chatRequest'] == null) {
            throw new runtime.RequiredError(
                'chatRequest',
                'Required parameter "chatRequest" was null or undefined when calling chatWithAgentApiV1ChatAgentIdConversationIdPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/chat/{agent_id}/{conversation_id}`;
        urlPath = urlPath.replace(`{${"agent_id"}}`, encodeURIComponent(String(requestParameters['agentId'])));
        urlPath = urlPath.replace(`{${"conversation_id"}}`, encodeURIComponent(String(requestParameters['conversationId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ChatRequestToJSON(requestParameters['chatRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Send a message to an agent within a specific conversation.
     * Chat With Agent
     */
    async chatWithAgentApiV1ChatAgentIdConversationIdPost(requestParameters: ChatWithAgentApiV1ChatAgentIdConversationIdPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.chatWithAgentApiV1ChatAgentIdConversationIdPostRaw(requestParameters, initOverrides);
    }

    /**
     * Like or dislike a message in a specific conversation.
     * Like Message
     */
    async likeMessageApiV1ChatAgentIdConversationIdLikePostRaw(requestParameters: LikeMessageApiV1ChatAgentIdConversationIdLikePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        if (requestParameters['agentId'] == null) {
            throw new runtime.RequiredError(
                'agentId',
                'Required parameter "agentId" was null or undefined when calling likeMessageApiV1ChatAgentIdConversationIdLikePost().'
            );
        }

        if (requestParameters['conversationId'] == null) {
            throw new runtime.RequiredError(
                'conversationId',
                'Required parameter "conversationId" was null or undefined when calling likeMessageApiV1ChatAgentIdConversationIdLikePost().'
            );
        }

        if (requestParameters['messageIndex'] == null) {
            throw new runtime.RequiredError(
                'messageIndex',
                'Required parameter "messageIndex" was null or undefined when calling likeMessageApiV1ChatAgentIdConversationIdLikePost().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['messageIndex'] != null) {
            queryParameters['message_index'] = requestParameters['messageIndex'];
        }

        if (requestParameters['liked'] != null) {
            queryParameters['liked'] = requestParameters['liked'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/chat/{agent_id}/{conversation_id}/like`;
        urlPath = urlPath.replace(`{${"agent_id"}}`, encodeURIComponent(String(requestParameters['agentId'])));
        urlPath = urlPath.replace(`{${"conversation_id"}}`, encodeURIComponent(String(requestParameters['conversationId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Like or dislike a message in a specific conversation.
     * Like Message
     */
    async likeMessageApiV1ChatAgentIdConversationIdLikePost(requestParameters: LikeMessageApiV1ChatAgentIdConversationIdLikePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.likeMessageApiV1ChatAgentIdConversationIdLikePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Select data sources for a specific conversation.
     * Select Conversation
     */
    async selectConversationApiV1ChatAgentIdConversationIdSelectPostRaw(requestParameters: SelectConversationApiV1ChatAgentIdConversationIdSelectPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['agentId'] == null) {
            throw new runtime.RequiredError(
                'agentId',
                'Required parameter "agentId" was null or undefined when calling selectConversationApiV1ChatAgentIdConversationIdSelectPost().'
            );
        }

        if (requestParameters['conversationId'] == null) {
            throw new runtime.RequiredError(
                'conversationId',
                'Required parameter "conversationId" was null or undefined when calling selectConversationApiV1ChatAgentIdConversationIdSelectPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/chat/{agent_id}/{conversation_id}/select`;
        urlPath = urlPath.replace(`{${"agent_id"}}`, encodeURIComponent(String(requestParameters['agentId'])));
        urlPath = urlPath.replace(`{${"conversation_id"}}`, encodeURIComponent(String(requestParameters['conversationId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Select data sources for a specific conversation.
     * Select Conversation
     */
    async selectConversationApiV1ChatAgentIdConversationIdSelectPost(requestParameters: SelectConversationApiV1ChatAgentIdConversationIdSelectPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.selectConversationApiV1ChatAgentIdConversationIdSelectPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
