/* tslint:disable */
/* eslint-disable */
/**
 * RAG API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiSchemasConversationsConversationInfo,
  ConversationCreate,
  ConversationUpdate,
  GenericException,
  HTTPValidationError,
} from '../models/index';
import {
    ApiSchemasConversationsConversationInfoFromJSON,
    ApiSchemasConversationsConversationInfoToJSON,
    ConversationCreateFromJSON,
    ConversationCreateToJSON,
    ConversationUpdateFromJSON,
    ConversationUpdateToJSON,
    GenericExceptionFromJSON,
    GenericExceptionToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/index';

export interface AddConversationApiV1ConversationsPostRequest {
    conversationCreate: ConversationCreate;
}

export interface DeleteConversationApiV1ConversationsConversationIdDeleteRequest {
    conversationId: string;
}

export interface ListConversationsApiV1ConversationsAgentIdGetRequest {
    agentId: string;
}

export interface UpdateConversationApiV1ConversationsConversationIdPatchRequest {
    conversationId: string;
    conversationUpdate: ConversationUpdate;
}

/**
 * 
 */
export class ConversationsApi extends runtime.BaseAPI {

    /**
     * Create a new conversation.
     * Add Conversation
     */
    async addConversationApiV1ConversationsPostRaw(requestParameters: AddConversationApiV1ConversationsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiSchemasConversationsConversationInfo>> {
        if (requestParameters['conversationCreate'] == null) {
            throw new runtime.RequiredError(
                'conversationCreate',
                'Required parameter "conversationCreate" was null or undefined when calling addConversationApiV1ConversationsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/conversations/`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ConversationCreateToJSON(requestParameters['conversationCreate']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiSchemasConversationsConversationInfoFromJSON(jsonValue));
    }

    /**
     * Create a new conversation.
     * Add Conversation
     */
    async addConversationApiV1ConversationsPost(requestParameters: AddConversationApiV1ConversationsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiSchemasConversationsConversationInfo> {
        const response = await this.addConversationApiV1ConversationsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete a conversation by ID.
     * Delete Conversation
     */
    async deleteConversationApiV1ConversationsConversationIdDeleteRaw(requestParameters: DeleteConversationApiV1ConversationsConversationIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['conversationId'] == null) {
            throw new runtime.RequiredError(
                'conversationId',
                'Required parameter "conversationId" was null or undefined when calling deleteConversationApiV1ConversationsConversationIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/conversations/{conversation_id}`;
        urlPath = urlPath.replace(`{${"conversation_id"}}`, encodeURIComponent(String(requestParameters['conversationId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Delete a conversation by ID.
     * Delete Conversation
     */
    async deleteConversationApiV1ConversationsConversationIdDelete(requestParameters: DeleteConversationApiV1ConversationsConversationIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.deleteConversationApiV1ConversationsConversationIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List conversations for a given user.
     * List Conversations
     */
    async listConversationsApiV1ConversationsAgentIdGetRaw(requestParameters: ListConversationsApiV1ConversationsAgentIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ApiSchemasConversationsConversationInfo>>> {
        if (requestParameters['agentId'] == null) {
            throw new runtime.RequiredError(
                'agentId',
                'Required parameter "agentId" was null or undefined when calling listConversationsApiV1ConversationsAgentIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/conversations/{agent_id}`;
        urlPath = urlPath.replace(`{${"agent_id"}}`, encodeURIComponent(String(requestParameters['agentId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ApiSchemasConversationsConversationInfoFromJSON));
    }

    /**
     * List conversations for a given user.
     * List Conversations
     */
    async listConversationsApiV1ConversationsAgentIdGet(requestParameters: ListConversationsApiV1ConversationsAgentIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ApiSchemasConversationsConversationInfo>> {
        const response = await this.listConversationsApiV1ConversationsAgentIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update a conversation by ID.
     * Update Conversation
     */
    async updateConversationApiV1ConversationsConversationIdPatchRaw(requestParameters: UpdateConversationApiV1ConversationsConversationIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiSchemasConversationsConversationInfo>> {
        if (requestParameters['conversationId'] == null) {
            throw new runtime.RequiredError(
                'conversationId',
                'Required parameter "conversationId" was null or undefined when calling updateConversationApiV1ConversationsConversationIdPatch().'
            );
        }

        if (requestParameters['conversationUpdate'] == null) {
            throw new runtime.RequiredError(
                'conversationUpdate',
                'Required parameter "conversationUpdate" was null or undefined when calling updateConversationApiV1ConversationsConversationIdPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/conversations/{conversation_id}`;
        urlPath = urlPath.replace(`{${"conversation_id"}}`, encodeURIComponent(String(requestParameters['conversationId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: ConversationUpdateToJSON(requestParameters['conversationUpdate']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiSchemasConversationsConversationInfoFromJSON(jsonValue));
    }

    /**
     * Update a conversation by ID.
     * Update Conversation
     */
    async updateConversationApiV1ConversationsConversationIdPatch(requestParameters: UpdateConversationApiV1ConversationsConversationIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiSchemasConversationsConversationInfo> {
        const response = await this.updateConversationApiV1ConversationsConversationIdPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
