/* tslint:disable */
/* eslint-disable */
/**
 * RAG API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  EmbeddingCreate,
  EmbeddingInfo,
  GenericException,
  HTTPValidationError,
} from '../models/index';
import {
    EmbeddingCreateFromJSON,
    EmbeddingCreateToJSON,
    EmbeddingInfoFromJSON,
    EmbeddingInfoToJSON,
    GenericExceptionFromJSON,
    GenericExceptionToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/index';

export interface AddEmbeddingApiV1EmbeddingsEmbeddingPostRequest {
    embeddingCreate: EmbeddingCreate;
}

export interface DeleteEmbeddingApiV1EmbeddingsEmbeddingEmbeddingNameDeleteRequest {
    embeddingName: string;
}

export interface GetEmbeddingApiV1EmbeddingsEmbeddingEmbeddingNameGetRequest {
    embeddingName: string;
}

export interface GetEmbeddingVendorDescApiV1EmbeddingsVendorVendorNameGetRequest {
    vendorName: string;
}

export interface UpdateEmbeddingApiV1EmbeddingsEmbeddingEmbeddingNamePatchRequest {
    embeddingName: string;
    requestBody: { [key: string]: any; };
    _default?: boolean;
}

/**
 * 
 */
export class EmbeddingsApi extends runtime.BaseAPI {

    /**
     * Add Embedding
     */
    async addEmbeddingApiV1EmbeddingsEmbeddingPostRaw(requestParameters: AddEmbeddingApiV1EmbeddingsEmbeddingPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['embeddingCreate'] == null) {
            throw new runtime.RequiredError(
                'embeddingCreate',
                'Required parameter "embeddingCreate" was null or undefined when calling addEmbeddingApiV1EmbeddingsEmbeddingPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/embeddings/embedding`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: EmbeddingCreateToJSON(requestParameters['embeddingCreate']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Add Embedding
     */
    async addEmbeddingApiV1EmbeddingsEmbeddingPost(requestParameters: AddEmbeddingApiV1EmbeddingsEmbeddingPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.addEmbeddingApiV1EmbeddingsEmbeddingPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete Embedding
     */
    async deleteEmbeddingApiV1EmbeddingsEmbeddingEmbeddingNameDeleteRaw(requestParameters: DeleteEmbeddingApiV1EmbeddingsEmbeddingEmbeddingNameDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['embeddingName'] == null) {
            throw new runtime.RequiredError(
                'embeddingName',
                'Required parameter "embeddingName" was null or undefined when calling deleteEmbeddingApiV1EmbeddingsEmbeddingEmbeddingNameDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/embeddings/embedding/{embedding_name}`;
        urlPath = urlPath.replace(`{${"embedding_name"}}`, encodeURIComponent(String(requestParameters['embeddingName'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Delete Embedding
     */
    async deleteEmbeddingApiV1EmbeddingsEmbeddingEmbeddingNameDelete(requestParameters: DeleteEmbeddingApiV1EmbeddingsEmbeddingEmbeddingNameDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.deleteEmbeddingApiV1EmbeddingsEmbeddingEmbeddingNameDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Embedding
     */
    async getEmbeddingApiV1EmbeddingsEmbeddingEmbeddingNameGetRaw(requestParameters: GetEmbeddingApiV1EmbeddingsEmbeddingEmbeddingNameGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EmbeddingInfo>> {
        if (requestParameters['embeddingName'] == null) {
            throw new runtime.RequiredError(
                'embeddingName',
                'Required parameter "embeddingName" was null or undefined when calling getEmbeddingApiV1EmbeddingsEmbeddingEmbeddingNameGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/embeddings/embedding/{embedding_name}`;
        urlPath = urlPath.replace(`{${"embedding_name"}}`, encodeURIComponent(String(requestParameters['embeddingName'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EmbeddingInfoFromJSON(jsonValue));
    }

    /**
     * Get Embedding
     */
    async getEmbeddingApiV1EmbeddingsEmbeddingEmbeddingNameGet(requestParameters: GetEmbeddingApiV1EmbeddingsEmbeddingEmbeddingNameGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EmbeddingInfo> {
        const response = await this.getEmbeddingApiV1EmbeddingsEmbeddingEmbeddingNameGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Embedding Vendor Desc
     */
    async getEmbeddingVendorDescApiV1EmbeddingsVendorVendorNameGetRaw(requestParameters: GetEmbeddingVendorDescApiV1EmbeddingsVendorVendorNameGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['vendorName'] == null) {
            throw new runtime.RequiredError(
                'vendorName',
                'Required parameter "vendorName" was null or undefined when calling getEmbeddingVendorDescApiV1EmbeddingsVendorVendorNameGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/embeddings/vendor/{vendor_name}`;
        urlPath = urlPath.replace(`{${"vendor_name"}}`, encodeURIComponent(String(requestParameters['vendorName'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Get Embedding Vendor Desc
     */
    async getEmbeddingVendorDescApiV1EmbeddingsVendorVendorNameGet(requestParameters: GetEmbeddingVendorDescApiV1EmbeddingsVendorVendorNameGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.getEmbeddingVendorDescApiV1EmbeddingsVendorVendorNameGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List Embedding Vendors
     */
    async listEmbeddingVendorsApiV1EmbeddingsVendorsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/embeddings/vendors`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * List Embedding Vendors
     */
    async listEmbeddingVendorsApiV1EmbeddingsVendorsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.listEmbeddingVendorsApiV1EmbeddingsVendorsGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * List Embeddings
     */
    async listEmbeddingsApiV1EmbeddingsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: EmbeddingInfo; }>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/embeddings/`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => runtime.mapValues(jsonValue, EmbeddingInfoFromJSON));
    }

    /**
     * List Embeddings
     */
    async listEmbeddingsApiV1EmbeddingsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: EmbeddingInfo; }> {
        const response = await this.listEmbeddingsApiV1EmbeddingsGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Update Embedding
     */
    async updateEmbeddingApiV1EmbeddingsEmbeddingEmbeddingNamePatchRaw(requestParameters: UpdateEmbeddingApiV1EmbeddingsEmbeddingEmbeddingNamePatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['embeddingName'] == null) {
            throw new runtime.RequiredError(
                'embeddingName',
                'Required parameter "embeddingName" was null or undefined when calling updateEmbeddingApiV1EmbeddingsEmbeddingEmbeddingNamePatch().'
            );
        }

        if (requestParameters['requestBody'] == null) {
            throw new runtime.RequiredError(
                'requestBody',
                'Required parameter "requestBody" was null or undefined when calling updateEmbeddingApiV1EmbeddingsEmbeddingEmbeddingNamePatch().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['_default'] != null) {
            queryParameters['default'] = requestParameters['_default'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/embeddings/embedding/{embedding_name}`;
        urlPath = urlPath.replace(`{${"embedding_name"}}`, encodeURIComponent(String(requestParameters['embeddingName'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['requestBody'],
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Update Embedding
     */
    async updateEmbeddingApiV1EmbeddingsEmbeddingEmbeddingNamePatch(requestParameters: UpdateEmbeddingApiV1EmbeddingsEmbeddingEmbeddingNamePatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.updateEmbeddingApiV1EmbeddingsEmbeddingEmbeddingNamePatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
