/* tslint:disable */
/* eslint-disable */
/**
 * RAG API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GenericException,
  HTTPValidationError,
  IndexInfo,
} from '../models/index';
import {
    GenericExceptionFromJSON,
    GenericExceptionToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    IndexInfoFromJSON,
    IndexInfoToJSON,
} from '../models/index';

export interface CreateIndexApiV1IndexPostRequest {
    name: string;
    indexType: string;
    body: object;
}

export interface DeleteIndexApiV1IndexIndexIndexIdDeleteRequest {
    indexId: number;
}

export interface GetIndexApiV1IndexIndexIndexIdGetRequest {
    indexId: number;
}

export interface IndexFilesApiV1IndexIndexIndexIdIndexFilesPostRequest {
    indexId: number;
    files: Array<Blob>;
    reindex?: boolean;
}

export interface ListFilesApiV1IndexIndexIndexIdGetRequest {
    indexId: number;
    namePattern?: string;
}

export interface ListGroupsApiV1IndexIndexIndexIdGroupsGetRequest {
    indexId: number;
}

/**
 * 
 */
export class IndexApi extends runtime.BaseAPI {

    /**
     * Create Index
     */
    async createIndexApiV1IndexPostRaw(requestParameters: CreateIndexApiV1IndexPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IndexInfo>> {
        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling createIndexApiV1IndexPost().'
            );
        }

        if (requestParameters['indexType'] == null) {
            throw new runtime.RequiredError(
                'indexType',
                'Required parameter "indexType" was null or undefined when calling createIndexApiV1IndexPost().'
            );
        }

        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling createIndexApiV1IndexPost().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['name'] != null) {
            queryParameters['name'] = requestParameters['name'];
        }

        if (requestParameters['indexType'] != null) {
            queryParameters['index_type'] = requestParameters['indexType'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/index/`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IndexInfoFromJSON(jsonValue));
    }

    /**
     * Create Index
     */
    async createIndexApiV1IndexPost(requestParameters: CreateIndexApiV1IndexPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IndexInfo> {
        const response = await this.createIndexApiV1IndexPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete Index
     */
    async deleteIndexApiV1IndexIndexIndexIdDeleteRaw(requestParameters: DeleteIndexApiV1IndexIndexIndexIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['indexId'] == null) {
            throw new runtime.RequiredError(
                'indexId',
                'Required parameter "indexId" was null or undefined when calling deleteIndexApiV1IndexIndexIndexIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/index/index/{index_id}`;
        urlPath = urlPath.replace(`{${"index_id"}}`, encodeURIComponent(String(requestParameters['indexId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Delete Index
     */
    async deleteIndexApiV1IndexIndexIndexIdDelete(requestParameters: DeleteIndexApiV1IndexIndexIndexIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.deleteIndexApiV1IndexIndexIndexIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Index
     */
    async getIndexApiV1IndexIndexIndexIdGetRaw(requestParameters: GetIndexApiV1IndexIndexIndexIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IndexInfo>> {
        if (requestParameters['indexId'] == null) {
            throw new runtime.RequiredError(
                'indexId',
                'Required parameter "indexId" was null or undefined when calling getIndexApiV1IndexIndexIndexIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/index/index/{index_id}`;
        urlPath = urlPath.replace(`{${"index_id"}}`, encodeURIComponent(String(requestParameters['indexId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IndexInfoFromJSON(jsonValue));
    }

    /**
     * Get Index
     */
    async getIndexApiV1IndexIndexIndexIdGet(requestParameters: GetIndexApiV1IndexIndexIndexIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IndexInfo> {
        const response = await this.getIndexApiV1IndexIndexIndexIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Index Files
     */
    async indexFilesApiV1IndexIndexIndexIdIndexFilesPostRaw(requestParameters: IndexFilesApiV1IndexIndexIndexIdIndexFilesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['indexId'] == null) {
            throw new runtime.RequiredError(
                'indexId',
                'Required parameter "indexId" was null or undefined when calling indexFilesApiV1IndexIndexIndexIdIndexFilesPost().'
            );
        }

        if (requestParameters['files'] == null) {
            throw new runtime.RequiredError(
                'files',
                'Required parameter "files" was null or undefined when calling indexFilesApiV1IndexIndexIndexIdIndexFilesPost().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['reindex'] != null) {
            queryParameters['reindex'] = requestParameters['reindex'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['files'] != null) {
            requestParameters['files'].forEach((element) => {
                formParams.append('files', element as any);
            })
        }


        let urlPath = `/api/v1/index/index/{index_id}/index_files`;
        urlPath = urlPath.replace(`{${"index_id"}}`, encodeURIComponent(String(requestParameters['indexId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Index Files
     */
    async indexFilesApiV1IndexIndexIndexIdIndexFilesPost(requestParameters: IndexFilesApiV1IndexIndexIndexIdIndexFilesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.indexFilesApiV1IndexIndexIndexIdIndexFilesPostRaw(requestParameters, initOverrides);
    }

    /**
     * List Files
     */
    async listFilesApiV1IndexIndexIndexIdGetRaw(requestParameters: ListFilesApiV1IndexIndexIndexIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['indexId'] == null) {
            throw new runtime.RequiredError(
                'indexId',
                'Required parameter "indexId" was null or undefined when calling listFilesApiV1IndexIndexIndexIdGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['namePattern'] != null) {
            queryParameters['name_pattern'] = requestParameters['namePattern'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/index/index/{index_id}/`;
        urlPath = urlPath.replace(`{${"index_id"}}`, encodeURIComponent(String(requestParameters['indexId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * List Files
     */
    async listFilesApiV1IndexIndexIndexIdGet(requestParameters: ListFilesApiV1IndexIndexIndexIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.listFilesApiV1IndexIndexIndexIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List Groups
     */
    async listGroupsApiV1IndexIndexIndexIdGroupsGetRaw(requestParameters: ListGroupsApiV1IndexIndexIndexIdGroupsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['indexId'] == null) {
            throw new runtime.RequiredError(
                'indexId',
                'Required parameter "indexId" was null or undefined when calling listGroupsApiV1IndexIndexIndexIdGroupsGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/index/index/{index_id}/groups`;
        urlPath = urlPath.replace(`{${"index_id"}}`, encodeURIComponent(String(requestParameters['indexId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * List Groups
     */
    async listGroupsApiV1IndexIndexIndexIdGroupsGet(requestParameters: ListGroupsApiV1IndexIndexIndexIdGroupsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.listGroupsApiV1IndexIndexIndexIdGroupsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List Index Types
     */
    async listIndexTypesApiV1IndexTypesGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/index/types`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * List Index Types
     */
    async listIndexTypesApiV1IndexTypesGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.listIndexTypesApiV1IndexTypesGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * List Indices
     */
    async listIndicesApiV1IndexGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<IndexInfo>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/index/`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(IndexInfoFromJSON));
    }

    /**
     * List Indices
     */
    async listIndicesApiV1IndexGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<IndexInfo>> {
        const response = await this.listIndicesApiV1IndexGetRaw(initOverrides);
        return await response.value();
    }

}
