/* tslint:disable */
/* eslint-disable */
/**
 * RAG API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BodyUpdateGroupApiV1IndexIndexIdGroupsGroupIdPatch,
  FileInfo,
  GenericException,
  GroupInfo,
  HTTPValidationError,
  IndexInfo,
} from '../models/index';
import {
    BodyUpdateGroupApiV1IndexIndexIdGroupsGroupIdPatchFromJSON,
    BodyUpdateGroupApiV1IndexIndexIdGroupsGroupIdPatchToJSON,
    FileInfoFromJSON,
    FileInfoToJSON,
    GenericExceptionFromJSON,
    GenericExceptionToJSON,
    GroupInfoFromJSON,
    GroupInfoToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    IndexInfoFromJSON,
    IndexInfoToJSON,
} from '../models/index';

export interface CreateGroupApiV1IndexIndexIdGroupsPostRequest {
    indexId: string;
    groupName: string;
    requestBody: Array<string | null>;
}

export interface CreateIndexApiV1IndexPostRequest {
    name: string;
    indexType: string;
    body?: object | null;
}

export interface DeleteAllFilesApiV1IndexIndexIdFilesDeleteRequest {
    indexId: string;
}

export interface DeleteFileApiV1IndexIndexIdFilesFileIdDeleteRequest {
    indexId: string;
    fileId: string;
}

export interface DeleteGroupApiV1IndexIndexIdGroupsGroupIdDeleteRequest {
    indexId: string;
    groupId: string;
}

export interface DeleteIndexApiV1IndexIndexIdDeleteRequest {
    indexId: string;
}

export interface GetAdminSettingsApiV1IndexAdminSettingsGetRequest {
    indexType: string;
}

export interface GetIndexApiV1IndexIndexIdGetRequest {
    indexId: string;
}

export interface GetIndexSettingsApiV1IndexIndexIdSettingsGetRequest {
    indexId: string;
}

export interface IndexFilesApiV1IndexIndexPostRequest {
    agentId: string;
    files: Array<Blob>;
    reindex?: boolean;
}

export interface ListFilesApiV1IndexIndexIdFilesGetRequest {
    indexId: string;
    namePattern?: string;
}

export interface ListGroupsApiV1IndexIndexIdGroupsGetRequest {
    indexId: string;
}

export interface UpdateGroupApiV1IndexIndexIdGroupsGroupIdPatchRequest {
    indexId: string;
    groupId: string;
    groupName?: string | null;
    bodyUpdateGroupApiV1IndexIndexIdGroupsGroupIdPatch?: BodyUpdateGroupApiV1IndexIndexIdGroupsGroupIdPatch;
}

export interface UpdateIndexApiV1IndexIndexIdPatchRequest {
    indexId: string;
    name?: string | null;
    body?: object | null;
}

/**
 * 
 */
export class IndexApi extends runtime.BaseAPI {

    /**
     * Create Group
     */
    async createGroupApiV1IndexIndexIdGroupsPostRaw(requestParameters: CreateGroupApiV1IndexIndexIdGroupsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['indexId'] == null) {
            throw new runtime.RequiredError(
                'indexId',
                'Required parameter "indexId" was null or undefined when calling createGroupApiV1IndexIndexIdGroupsPost().'
            );
        }

        if (requestParameters['groupName'] == null) {
            throw new runtime.RequiredError(
                'groupName',
                'Required parameter "groupName" was null or undefined when calling createGroupApiV1IndexIndexIdGroupsPost().'
            );
        }

        if (requestParameters['requestBody'] == null) {
            throw new runtime.RequiredError(
                'requestBody',
                'Required parameter "requestBody" was null or undefined when calling createGroupApiV1IndexIndexIdGroupsPost().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['groupName'] != null) {
            queryParameters['group_name'] = requestParameters['groupName'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/index/{index_id}/groups`;
        urlPath = urlPath.replace(`{${"index_id"}}`, encodeURIComponent(String(requestParameters['indexId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['requestBody'],
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Create Group
     */
    async createGroupApiV1IndexIndexIdGroupsPost(requestParameters: CreateGroupApiV1IndexIndexIdGroupsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.createGroupApiV1IndexIndexIdGroupsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create Index
     */
    async createIndexApiV1IndexPostRaw(requestParameters: CreateIndexApiV1IndexPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IndexInfo>> {
        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling createIndexApiV1IndexPost().'
            );
        }

        if (requestParameters['indexType'] == null) {
            throw new runtime.RequiredError(
                'indexType',
                'Required parameter "indexType" was null or undefined when calling createIndexApiV1IndexPost().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['name'] != null) {
            queryParameters['name'] = requestParameters['name'];
        }

        if (requestParameters['indexType'] != null) {
            queryParameters['index_type'] = requestParameters['indexType'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/index/`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IndexInfoFromJSON(jsonValue));
    }

    /**
     * Create Index
     */
    async createIndexApiV1IndexPost(requestParameters: CreateIndexApiV1IndexPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IndexInfo> {
        const response = await this.createIndexApiV1IndexPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete All Files
     */
    async deleteAllFilesApiV1IndexIndexIdFilesDeleteRaw(requestParameters: DeleteAllFilesApiV1IndexIndexIdFilesDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<string | null>>> {
        if (requestParameters['indexId'] == null) {
            throw new runtime.RequiredError(
                'indexId',
                'Required parameter "indexId" was null or undefined when calling deleteAllFilesApiV1IndexIndexIdFilesDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/index/{index_id}/files`;
        urlPath = urlPath.replace(`{${"index_id"}}`, encodeURIComponent(String(requestParameters['indexId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Delete All Files
     */
    async deleteAllFilesApiV1IndexIndexIdFilesDelete(requestParameters: DeleteAllFilesApiV1IndexIndexIdFilesDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<string | null>> {
        const response = await this.deleteAllFilesApiV1IndexIndexIdFilesDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete File
     */
    async deleteFileApiV1IndexIndexIdFilesFileIdDeleteRaw(requestParameters: DeleteFileApiV1IndexIndexIdFilesFileIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        if (requestParameters['indexId'] == null) {
            throw new runtime.RequiredError(
                'indexId',
                'Required parameter "indexId" was null or undefined when calling deleteFileApiV1IndexIndexIdFilesFileIdDelete().'
            );
        }

        if (requestParameters['fileId'] == null) {
            throw new runtime.RequiredError(
                'fileId',
                'Required parameter "fileId" was null or undefined when calling deleteFileApiV1IndexIndexIdFilesFileIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/index/{index_id}/files/{file_id}`;
        urlPath = urlPath.replace(`{${"index_id"}}`, encodeURIComponent(String(requestParameters['indexId'])));
        urlPath = urlPath.replace(`{${"file_id"}}`, encodeURIComponent(String(requestParameters['fileId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Delete File
     */
    async deleteFileApiV1IndexIndexIdFilesFileIdDelete(requestParameters: DeleteFileApiV1IndexIndexIdFilesFileIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.deleteFileApiV1IndexIndexIdFilesFileIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete Group
     */
    async deleteGroupApiV1IndexIndexIdGroupsGroupIdDeleteRaw(requestParameters: DeleteGroupApiV1IndexIndexIdGroupsGroupIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['indexId'] == null) {
            throw new runtime.RequiredError(
                'indexId',
                'Required parameter "indexId" was null or undefined when calling deleteGroupApiV1IndexIndexIdGroupsGroupIdDelete().'
            );
        }

        if (requestParameters['groupId'] == null) {
            throw new runtime.RequiredError(
                'groupId',
                'Required parameter "groupId" was null or undefined when calling deleteGroupApiV1IndexIndexIdGroupsGroupIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/index/{index_id}/groups/{group_id}`;
        urlPath = urlPath.replace(`{${"index_id"}}`, encodeURIComponent(String(requestParameters['indexId'])));
        urlPath = urlPath.replace(`{${"group_id"}}`, encodeURIComponent(String(requestParameters['groupId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Delete Group
     */
    async deleteGroupApiV1IndexIndexIdGroupsGroupIdDelete(requestParameters: DeleteGroupApiV1IndexIndexIdGroupsGroupIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.deleteGroupApiV1IndexIndexIdGroupsGroupIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete Index
     */
    async deleteIndexApiV1IndexIndexIdDeleteRaw(requestParameters: DeleteIndexApiV1IndexIndexIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['indexId'] == null) {
            throw new runtime.RequiredError(
                'indexId',
                'Required parameter "indexId" was null or undefined when calling deleteIndexApiV1IndexIndexIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/index/{index_id}`;
        urlPath = urlPath.replace(`{${"index_id"}}`, encodeURIComponent(String(requestParameters['indexId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Delete Index
     */
    async deleteIndexApiV1IndexIndexIdDelete(requestParameters: DeleteIndexApiV1IndexIndexIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.deleteIndexApiV1IndexIndexIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Admin Settings
     */
    async getAdminSettingsApiV1IndexAdminSettingsGetRaw(requestParameters: GetAdminSettingsApiV1IndexAdminSettingsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        if (requestParameters['indexType'] == null) {
            throw new runtime.RequiredError(
                'indexType',
                'Required parameter "indexType" was null or undefined when calling getAdminSettingsApiV1IndexAdminSettingsGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['indexType'] != null) {
            queryParameters['index_type'] = requestParameters['indexType'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/index/admin_settings`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Get Admin Settings
     */
    async getAdminSettingsApiV1IndexAdminSettingsGet(requestParameters: GetAdminSettingsApiV1IndexAdminSettingsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.getAdminSettingsApiV1IndexAdminSettingsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Index
     */
    async getIndexApiV1IndexIndexIdGetRaw(requestParameters: GetIndexApiV1IndexIndexIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IndexInfo>> {
        if (requestParameters['indexId'] == null) {
            throw new runtime.RequiredError(
                'indexId',
                'Required parameter "indexId" was null or undefined when calling getIndexApiV1IndexIndexIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/index/{index_id}`;
        urlPath = urlPath.replace(`{${"index_id"}}`, encodeURIComponent(String(requestParameters['indexId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IndexInfoFromJSON(jsonValue));
    }

    /**
     * Get Index
     */
    async getIndexApiV1IndexIndexIdGet(requestParameters: GetIndexApiV1IndexIndexIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IndexInfo> {
        const response = await this.getIndexApiV1IndexIndexIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Index Settings
     */
    async getIndexSettingsApiV1IndexIndexIdSettingsGetRaw(requestParameters: GetIndexSettingsApiV1IndexIndexIdSettingsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        if (requestParameters['indexId'] == null) {
            throw new runtime.RequiredError(
                'indexId',
                'Required parameter "indexId" was null or undefined when calling getIndexSettingsApiV1IndexIndexIdSettingsGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/index/{index_id}/settings`;
        urlPath = urlPath.replace(`{${"index_id"}}`, encodeURIComponent(String(requestParameters['indexId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Get Index Settings
     */
    async getIndexSettingsApiV1IndexIndexIdSettingsGet(requestParameters: GetIndexSettingsApiV1IndexIndexIdSettingsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.getIndexSettingsApiV1IndexIndexIdSettingsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Index Files
     */
    async indexFilesApiV1IndexIndexPostRaw(requestParameters: IndexFilesApiV1IndexIndexPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['agentId'] == null) {
            throw new runtime.RequiredError(
                'agentId',
                'Required parameter "agentId" was null or undefined when calling indexFilesApiV1IndexIndexPost().'
            );
        }

        if (requestParameters['files'] == null) {
            throw new runtime.RequiredError(
                'files',
                'Required parameter "files" was null or undefined when calling indexFilesApiV1IndexIndexPost().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['agentId'] != null) {
            queryParameters['agent_id'] = requestParameters['agentId'];
        }

        if (requestParameters['reindex'] != null) {
            queryParameters['reindex'] = requestParameters['reindex'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['files'] != null) {
            requestParameters['files'].forEach((element) => {
                formParams.append('files', element as any);
            })
        }


        let urlPath = `/api/v1/index/index`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Index Files
     */
    async indexFilesApiV1IndexIndexPost(requestParameters: IndexFilesApiV1IndexIndexPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.indexFilesApiV1IndexIndexPostRaw(requestParameters, initOverrides);
    }

    /**
     * List Files
     */
    async listFilesApiV1IndexIndexIdFilesGetRaw(requestParameters: ListFilesApiV1IndexIndexIdFilesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<FileInfo>>> {
        if (requestParameters['indexId'] == null) {
            throw new runtime.RequiredError(
                'indexId',
                'Required parameter "indexId" was null or undefined when calling listFilesApiV1IndexIndexIdFilesGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['namePattern'] != null) {
            queryParameters['name_pattern'] = requestParameters['namePattern'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/index/{index_id}/files`;
        urlPath = urlPath.replace(`{${"index_id"}}`, encodeURIComponent(String(requestParameters['indexId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(FileInfoFromJSON));
    }

    /**
     * List Files
     */
    async listFilesApiV1IndexIndexIdFilesGet(requestParameters: ListFilesApiV1IndexIndexIdFilesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<FileInfo>> {
        const response = await this.listFilesApiV1IndexIndexIdFilesGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List Groups
     */
    async listGroupsApiV1IndexIndexIdGroupsGetRaw(requestParameters: ListGroupsApiV1IndexIndexIdGroupsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<GroupInfo>>> {
        if (requestParameters['indexId'] == null) {
            throw new runtime.RequiredError(
                'indexId',
                'Required parameter "indexId" was null or undefined when calling listGroupsApiV1IndexIndexIdGroupsGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/index/{index_id}/groups`;
        urlPath = urlPath.replace(`{${"index_id"}}`, encodeURIComponent(String(requestParameters['indexId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(GroupInfoFromJSON));
    }

    /**
     * List Groups
     */
    async listGroupsApiV1IndexIndexIdGroupsGet(requestParameters: ListGroupsApiV1IndexIndexIdGroupsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<GroupInfo>> {
        const response = await this.listGroupsApiV1IndexIndexIdGroupsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List Index Types
     */
    async listIndexTypesApiV1IndexTypesGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<string | null>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/index/types`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * List Index Types
     */
    async listIndexTypesApiV1IndexTypesGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<string | null>> {
        const response = await this.listIndexTypesApiV1IndexTypesGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * List Indices
     */
    async listIndicesApiV1IndexGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<IndexInfo>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/index/`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(IndexInfoFromJSON));
    }

    /**
     * List Indices
     */
    async listIndicesApiV1IndexGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<IndexInfo>> {
        const response = await this.listIndicesApiV1IndexGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Update Group
     */
    async updateGroupApiV1IndexIndexIdGroupsGroupIdPatchRaw(requestParameters: UpdateGroupApiV1IndexIndexIdGroupsGroupIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['indexId'] == null) {
            throw new runtime.RequiredError(
                'indexId',
                'Required parameter "indexId" was null or undefined when calling updateGroupApiV1IndexIndexIdGroupsGroupIdPatch().'
            );
        }

        if (requestParameters['groupId'] == null) {
            throw new runtime.RequiredError(
                'groupId',
                'Required parameter "groupId" was null or undefined when calling updateGroupApiV1IndexIndexIdGroupsGroupIdPatch().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['groupName'] != null) {
            queryParameters['group_name'] = requestParameters['groupName'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/index/{index_id}/groups/{group_id}`;
        urlPath = urlPath.replace(`{${"index_id"}}`, encodeURIComponent(String(requestParameters['indexId'])));
        urlPath = urlPath.replace(`{${"group_id"}}`, encodeURIComponent(String(requestParameters['groupId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: BodyUpdateGroupApiV1IndexIndexIdGroupsGroupIdPatchToJSON(requestParameters['bodyUpdateGroupApiV1IndexIndexIdGroupsGroupIdPatch']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Update Group
     */
    async updateGroupApiV1IndexIndexIdGroupsGroupIdPatch(requestParameters: UpdateGroupApiV1IndexIndexIdGroupsGroupIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.updateGroupApiV1IndexIndexIdGroupsGroupIdPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update Index
     */
    async updateIndexApiV1IndexIndexIdPatchRaw(requestParameters: UpdateIndexApiV1IndexIndexIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['indexId'] == null) {
            throw new runtime.RequiredError(
                'indexId',
                'Required parameter "indexId" was null or undefined when calling updateIndexApiV1IndexIndexIdPatch().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['name'] != null) {
            queryParameters['name'] = requestParameters['name'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/index/{index_id}`;
        urlPath = urlPath.replace(`{${"index_id"}}`, encodeURIComponent(String(requestParameters['indexId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Update Index
     */
    async updateIndexApiV1IndexIndexIdPatch(requestParameters: UpdateIndexApiV1IndexIndexIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.updateIndexApiV1IndexIndexIdPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
