/* tslint:disable */
/* eslint-disable */
/**
 * RAG API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GenericException,
  HTTPValidationError,
  LlmCreate,
  LlmInfo,
} from '../models/index';
import {
    GenericExceptionFromJSON,
    GenericExceptionToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    LlmCreateFromJSON,
    LlmCreateToJSON,
    LlmInfoFromJSON,
    LlmInfoToJSON,
} from '../models/index';

export interface AddLlmApiV1LlmsLlmPostRequest {
    llmCreate: LlmCreate;
}

export interface DeleteLlmApiV1LlmsLlmLlmNameDeleteRequest {
    llmName: string;
}

export interface GetLlmApiV1LlmsLlmLlmNameGetRequest {
    llmName: string;
}

export interface GetVendorDescApiV1LlmsVendorVendorNameGetRequest {
    vendorName: string;
}

export interface UpdateLlmApiV1LlmsLlmLlmNamePatchRequest {
    llmName: string;
    body: object;
    _default?: boolean;
}

/**
 * 
 */
export class LlmsApi extends runtime.BaseAPI {

    /**
     * Add Llm
     */
    async addLlmApiV1LlmsLlmPostRaw(requestParameters: AddLlmApiV1LlmsLlmPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['llmCreate'] == null) {
            throw new runtime.RequiredError(
                'llmCreate',
                'Required parameter "llmCreate" was null or undefined when calling addLlmApiV1LlmsLlmPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/llms/llm`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: LlmCreateToJSON(requestParameters['llmCreate']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Add Llm
     */
    async addLlmApiV1LlmsLlmPost(requestParameters: AddLlmApiV1LlmsLlmPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.addLlmApiV1LlmsLlmPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete Llm
     */
    async deleteLlmApiV1LlmsLlmLlmNameDeleteRaw(requestParameters: DeleteLlmApiV1LlmsLlmLlmNameDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['llmName'] == null) {
            throw new runtime.RequiredError(
                'llmName',
                'Required parameter "llmName" was null or undefined when calling deleteLlmApiV1LlmsLlmLlmNameDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/llms/llm/{llm_name}`;
        urlPath = urlPath.replace(`{${"llm_name"}}`, encodeURIComponent(String(requestParameters['llmName'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Delete Llm
     */
    async deleteLlmApiV1LlmsLlmLlmNameDelete(requestParameters: DeleteLlmApiV1LlmsLlmLlmNameDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.deleteLlmApiV1LlmsLlmLlmNameDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Llm
     */
    async getLlmApiV1LlmsLlmLlmNameGetRaw(requestParameters: GetLlmApiV1LlmsLlmLlmNameGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LlmInfo>> {
        if (requestParameters['llmName'] == null) {
            throw new runtime.RequiredError(
                'llmName',
                'Required parameter "llmName" was null or undefined when calling getLlmApiV1LlmsLlmLlmNameGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/llms/llm/{llm_name}`;
        urlPath = urlPath.replace(`{${"llm_name"}}`, encodeURIComponent(String(requestParameters['llmName'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LlmInfoFromJSON(jsonValue));
    }

    /**
     * Get Llm
     */
    async getLlmApiV1LlmsLlmLlmNameGet(requestParameters: GetLlmApiV1LlmsLlmLlmNameGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LlmInfo> {
        const response = await this.getLlmApiV1LlmsLlmLlmNameGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Vendor Desc
     */
    async getVendorDescApiV1LlmsVendorVendorNameGetRaw(requestParameters: GetVendorDescApiV1LlmsVendorVendorNameGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['vendorName'] == null) {
            throw new runtime.RequiredError(
                'vendorName',
                'Required parameter "vendorName" was null or undefined when calling getVendorDescApiV1LlmsVendorVendorNameGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/llms/vendor/{vendor_name}`;
        urlPath = urlPath.replace(`{${"vendor_name"}}`, encodeURIComponent(String(requestParameters['vendorName'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Get Vendor Desc
     */
    async getVendorDescApiV1LlmsVendorVendorNameGet(requestParameters: GetVendorDescApiV1LlmsVendorVendorNameGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.getVendorDescApiV1LlmsVendorVendorNameGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List Llms
     */
    async listLlmsApiV1LlmsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: LlmInfo; }>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/llms/`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => runtime.mapValues(jsonValue, LlmInfoFromJSON));
    }

    /**
     * List Llms
     */
    async listLlmsApiV1LlmsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: LlmInfo; }> {
        const response = await this.listLlmsApiV1LlmsGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * List Vendors
     */
    async listVendorsApiV1LlmsVendorsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/llms/vendors`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * List Vendors
     */
    async listVendorsApiV1LlmsVendorsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.listVendorsApiV1LlmsVendorsGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Update Llm
     */
    async updateLlmApiV1LlmsLlmLlmNamePatchRaw(requestParameters: UpdateLlmApiV1LlmsLlmLlmNamePatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['llmName'] == null) {
            throw new runtime.RequiredError(
                'llmName',
                'Required parameter "llmName" was null or undefined when calling updateLlmApiV1LlmsLlmLlmNamePatch().'
            );
        }

        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling updateLlmApiV1LlmsLlmLlmNamePatch().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['_default'] != null) {
            queryParameters['default'] = requestParameters['_default'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/llms/llm/{llm_name}`;
        urlPath = urlPath.replace(`{${"llm_name"}}`, encodeURIComponent(String(requestParameters['llmName'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Update Llm
     */
    async updateLlmApiV1LlmsLlmLlmNamePatch(requestParameters: UpdateLlmApiV1LlmsLlmLlmNamePatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.updateLlmApiV1LlmsLlmLlmNamePatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
