/* tslint:disable */
/* eslint-disable */
/**
 * RAG API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GenericException,
  HTTPValidationError,
} from '../models/index';
import {
    GenericExceptionFromJSON,
    GenericExceptionToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/index';

export interface GetReasoningConfigApiV1ReasoningsReasoningNameConfigGetRequest {
    reasoningName: string;
}

/**
 * 
 */
export class ReasoningsApi extends runtime.BaseAPI {

    /**
     * Get Reasoning App Settings
     */
    async getReasoningAppSettingsApiV1ReasoningsSettingsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/reasonings/settings`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Get Reasoning App Settings
     */
    async getReasoningAppSettingsApiV1ReasoningsSettingsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.getReasoningAppSettingsApiV1ReasoningsSettingsGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Get Reasoning Config
     */
    async getReasoningConfigApiV1ReasoningsReasoningNameConfigGetRaw(requestParameters: GetReasoningConfigApiV1ReasoningsReasoningNameConfigGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        if (requestParameters['reasoningName'] == null) {
            throw new runtime.RequiredError(
                'reasoningName',
                'Required parameter "reasoningName" was null or undefined when calling getReasoningConfigApiV1ReasoningsReasoningNameConfigGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/reasonings/{reasoning_name}/config`;
        urlPath = urlPath.replace(`{${"reasoning_name"}}`, encodeURIComponent(String(requestParameters['reasoningName'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Get Reasoning Config
     */
    async getReasoningConfigApiV1ReasoningsReasoningNameConfigGet(requestParameters: GetReasoningConfigApiV1ReasoningsReasoningNameConfigGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.getReasoningConfigApiV1ReasoningsReasoningNameConfigGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List Reasonings
     */
    async listReasoningsApiV1ReasoningsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<string | null>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/reasonings/`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * List Reasonings
     */
    async listReasoningsApiV1ReasoningsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<string | null>> {
        const response = await this.listReasoningsApiV1ReasoningsGetRaw(initOverrides);
        return await response.value();
    }

}
