/* tslint:disable */
/* eslint-disable */
/**
 * RAG API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GenericException,
  HTTPValidationError,
  RerankingCreate,
  RerankingInfo,
} from '../models/index';
import {
    GenericExceptionFromJSON,
    GenericExceptionToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    RerankingCreateFromJSON,
    RerankingCreateToJSON,
    RerankingInfoFromJSON,
    RerankingInfoToJSON,
} from '../models/index';

export interface AddRerankingApiV1RerankingsRerankingPostRequest {
    rerankingCreate: RerankingCreate;
}

export interface DeleteRerankingApiV1RerankingsRerankingRerankingNameDeleteRequest {
    rerankingName: string;
}

export interface GetRerankingApiV1RerankingsRerankingRerankingNameGetRequest {
    rerankingName: string;
}

export interface GetRerankingVendorDescApiV1RerankingsVendorVendorNameGetRequest {
    vendorName: string;
}

export interface UpdateRerankingApiV1RerankingsRerankingRerankingNamePatchRequest {
    rerankingName: string;
    body: object;
    _default?: boolean;
}

/**
 * 
 */
export class RerankingsApi extends runtime.BaseAPI {

    /**
     * Add Reranking
     */
    async addRerankingApiV1RerankingsRerankingPostRaw(requestParameters: AddRerankingApiV1RerankingsRerankingPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['rerankingCreate'] == null) {
            throw new runtime.RequiredError(
                'rerankingCreate',
                'Required parameter "rerankingCreate" was null or undefined when calling addRerankingApiV1RerankingsRerankingPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/rerankings/reranking`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RerankingCreateToJSON(requestParameters['rerankingCreate']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Add Reranking
     */
    async addRerankingApiV1RerankingsRerankingPost(requestParameters: AddRerankingApiV1RerankingsRerankingPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.addRerankingApiV1RerankingsRerankingPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete Reranking
     */
    async deleteRerankingApiV1RerankingsRerankingRerankingNameDeleteRaw(requestParameters: DeleteRerankingApiV1RerankingsRerankingRerankingNameDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['rerankingName'] == null) {
            throw new runtime.RequiredError(
                'rerankingName',
                'Required parameter "rerankingName" was null or undefined when calling deleteRerankingApiV1RerankingsRerankingRerankingNameDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/rerankings/reranking/{reranking_name}`;
        urlPath = urlPath.replace(`{${"reranking_name"}}`, encodeURIComponent(String(requestParameters['rerankingName'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Delete Reranking
     */
    async deleteRerankingApiV1RerankingsRerankingRerankingNameDelete(requestParameters: DeleteRerankingApiV1RerankingsRerankingRerankingNameDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.deleteRerankingApiV1RerankingsRerankingRerankingNameDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Reranking
     */
    async getRerankingApiV1RerankingsRerankingRerankingNameGetRaw(requestParameters: GetRerankingApiV1RerankingsRerankingRerankingNameGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RerankingInfo>> {
        if (requestParameters['rerankingName'] == null) {
            throw new runtime.RequiredError(
                'rerankingName',
                'Required parameter "rerankingName" was null or undefined when calling getRerankingApiV1RerankingsRerankingRerankingNameGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/rerankings/reranking/{reranking_name}`;
        urlPath = urlPath.replace(`{${"reranking_name"}}`, encodeURIComponent(String(requestParameters['rerankingName'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RerankingInfoFromJSON(jsonValue));
    }

    /**
     * Get Reranking
     */
    async getRerankingApiV1RerankingsRerankingRerankingNameGet(requestParameters: GetRerankingApiV1RerankingsRerankingRerankingNameGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RerankingInfo> {
        const response = await this.getRerankingApiV1RerankingsRerankingRerankingNameGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Reranking Vendor Desc
     */
    async getRerankingVendorDescApiV1RerankingsVendorVendorNameGetRaw(requestParameters: GetRerankingVendorDescApiV1RerankingsVendorVendorNameGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['vendorName'] == null) {
            throw new runtime.RequiredError(
                'vendorName',
                'Required parameter "vendorName" was null or undefined when calling getRerankingVendorDescApiV1RerankingsVendorVendorNameGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/rerankings/vendor/{vendor_name}`;
        urlPath = urlPath.replace(`{${"vendor_name"}}`, encodeURIComponent(String(requestParameters['vendorName'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Get Reranking Vendor Desc
     */
    async getRerankingVendorDescApiV1RerankingsVendorVendorNameGet(requestParameters: GetRerankingVendorDescApiV1RerankingsVendorVendorNameGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.getRerankingVendorDescApiV1RerankingsVendorVendorNameGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List Reranking Vendors
     */
    async listRerankingVendorsApiV1RerankingsVendorsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/rerankings/vendors`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * List Reranking Vendors
     */
    async listRerankingVendorsApiV1RerankingsVendorsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.listRerankingVendorsApiV1RerankingsVendorsGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * List Rerankings
     */
    async listRerankingsApiV1RerankingsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/rerankings/`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * List Rerankings
     */
    async listRerankingsApiV1RerankingsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.listRerankingsApiV1RerankingsGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Update Reranking
     */
    async updateRerankingApiV1RerankingsRerankingRerankingNamePatchRaw(requestParameters: UpdateRerankingApiV1RerankingsRerankingRerankingNamePatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['rerankingName'] == null) {
            throw new runtime.RequiredError(
                'rerankingName',
                'Required parameter "rerankingName" was null or undefined when calling updateRerankingApiV1RerankingsRerankingRerankingNamePatch().'
            );
        }

        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling updateRerankingApiV1RerankingsRerankingRerankingNamePatch().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['_default'] != null) {
            queryParameters['default'] = requestParameters['_default'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/rerankings/reranking/{reranking_name}`;
        urlPath = urlPath.replace(`{${"reranking_name"}}`, encodeURIComponent(String(requestParameters['rerankingName'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Update Reranking
     */
    async updateRerankingApiV1RerankingsRerankingRerankingNamePatch(requestParameters: UpdateRerankingApiV1RerankingsRerankingRerankingNamePatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.updateRerankingApiV1RerankingsRerankingRerankingNamePatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
