/* tslint:disable */
/* eslint-disable */
/**
 * RAG API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 * Agent table
 * @export
 * @interface Agent
 */
export interface Agent {
  /**
   *
   * @type {string}
   * @memberof Agent
   */
  id?: string;
  /**
   *
   * @type {string}
   * @memberof Agent
   */
  name?: string;
  /**
   *
   * @type {string}
   * @memberof Agent
   */
  description?: string | null;
  /**
   *
   * @type {Date}
   * @memberof Agent
   */
  dateCreated?: Date;
  /**
   *
   * @type {number}
   * @memberof Agent
   */
  indexId?: number | null;
  /**
   *
   * @type {string}
   * @memberof Agent
   */
  modelName?: string | null;
}

/**
 * Check if a given object implements the Agent interface.
 */
export function instanceOfAgent(value: object): value is Agent {
  return true;
}

export function AgentFromJSON(json: any): Agent {
  return AgentFromJSONTyped(json, false);
}

export function AgentFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): Agent {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"] == null ? undefined : json["id"],
    name: json["name"] == null ? undefined : json["name"],
    description: json["description"] == null ? undefined : json["description"],
    dateCreated:
      json["date_created"] == null ? undefined : new Date(json["date_created"]),
    indexId: json["index_id"] == null ? undefined : json["index_id"],
    modelName: json["model_name"] == null ? undefined : json["model_name"],
  };
}

export function AgentToJSON(json: any): Agent {
  return AgentToJSONTyped(json, false);
}

export function AgentToJSONTyped(
  value?: Agent | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value["id"],
    name: value["name"],
    description: value["description"],
    date_created:
      value["dateCreated"] == null
        ? value["dateCreated"]
        : value["dateCreated"].toISOString(),
    index_id: value["indexId"],
    model_name: value["modelName"],
  };
}
