/* tslint:disable */
/* eslint-disable */
/**
 * RAG API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AgentCreate
 */
export interface AgentCreate {
    /**
     * 
     * @type {string}
     * @memberof AgentCreate
     */
    description?: string | null;
    /**
     * 
     * @type {number}
     * @memberof AgentCreate
     */
    indexId?: number | null;
    /**
     * 
     * @type {string}
     * @memberof AgentCreate
     */
    modelName?: string | null;
    /**
     * The name of the agent
     * @type {string}
     * @memberof AgentCreate
     */
    name: string;
}

/**
 * Check if a given object implements the AgentCreate interface.
 */
export function instanceOfAgentCreate(value: object): value is AgentCreate {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function AgentCreateFromJSON(json: any): AgentCreate {
    return AgentCreateFromJSONTyped(json, false);
}

export function AgentCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): AgentCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'] == null ? undefined : json['description'],
        'indexId': json['index_id'] == null ? undefined : json['index_id'],
        'modelName': json['model_name'] == null ? undefined : json['model_name'],
        'name': json['name'],
    };
}

export function AgentCreateToJSON(json: any): AgentCreate {
    return AgentCreateToJSONTyped(json, false);
}

export function AgentCreateToJSONTyped(value?: AgentCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
        'index_id': value['indexId'],
        'model_name': value['modelName'],
        'name': value['name'],
    };
}

