/* tslint:disable */
/* eslint-disable */
/**
 * RAG API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AgentResponse
 */
export interface AgentResponse {
    /**
     * 
     * @type {string}
     * @memberof AgentResponse
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AgentResponse
     */
    indexId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AgentResponse
     */
    reasoningId?: string | null;
    /**
     * The name of the agent
     * @type {string}
     * @memberof AgentResponse
     */
    name: string;
    /**
     * The unique identifier of the agent
     * @type {string}
     * @memberof AgentResponse
     */
    id: string;
    /**
     * The date the agent was created
     * @type {Date}
     * @memberof AgentResponse
     */
    dateCreated: Date;
}

/**
 * Check if a given object implements the AgentResponse interface.
 */
export function instanceOfAgentResponse(value: object): value is AgentResponse {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('dateCreated' in value) || value['dateCreated'] === undefined) return false;
    return true;
}

export function AgentResponseFromJSON(json: any): AgentResponse {
    return AgentResponseFromJSONTyped(json, false);
}

export function AgentResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AgentResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'] == null ? undefined : json['description'],
        'indexId': json['index_id'] == null ? undefined : json['index_id'],
        'reasoningId': json['reasoning_id'] == null ? undefined : json['reasoning_id'],
        'name': json['name'],
        'id': json['id'],
        'dateCreated': (new Date(json['date_created'])),
    };
}

export function AgentResponseToJSON(json: any): AgentResponse {
    return AgentResponseToJSONTyped(json, false);
}

export function AgentResponseToJSONTyped(value?: AgentResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
        'index_id': value['indexId'],
        'reasoning_id': value['reasoningId'],
        'name': value['name'],
        'id': value['id'],
        'date_created': value['dateCreated'].toISOString(),
    };
}

