/* tslint:disable */
/* eslint-disable */
/**
 * RAG API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AgentUsersAndCreatorsResponse
 */
export interface AgentUsersAndCreatorsResponse {
    /**
     * List of the usernames of creators associated with the agent
     * @type {Array<string>}
     * @memberof AgentUsersAndCreatorsResponse
     */
    creators: Array<string>;
    /**
     * List of usernames associated with the agent
     * @type {Array<string>}
     * @memberof AgentUsersAndCreatorsResponse
     */
    users: Array<string>;
}

/**
 * Check if a given object implements the AgentUsersAndCreatorsResponse interface.
 */
export function instanceOfAgentUsersAndCreatorsResponse(value: object): value is AgentUsersAndCreatorsResponse {
    if (!('creators' in value) || value['creators'] === undefined) return false;
    if (!('users' in value) || value['users'] === undefined) return false;
    return true;
}

export function AgentUsersAndCreatorsResponseFromJSON(json: any): AgentUsersAndCreatorsResponse {
    return AgentUsersAndCreatorsResponseFromJSONTyped(json, false);
}

export function AgentUsersAndCreatorsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AgentUsersAndCreatorsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'creators': json['creators'],
        'users': json['users'],
    };
}

export function AgentUsersAndCreatorsResponseToJSON(json: any): AgentUsersAndCreatorsResponse {
    return AgentUsersAndCreatorsResponseToJSONTyped(json, false);
}

export function AgentUsersAndCreatorsResponseToJSONTyped(value?: AgentUsersAndCreatorsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'creators': value['creators'],
        'users': value['users'],
    };
}

