/* tslint:disable */
/* eslint-disable */
/**
 * RAG API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AgentUpdate
 */
export interface AgentUpdate {
    /**
     * 
     * @type {string}
     * @memberof AgentUpdate
     */
    description?: string | null;
    /**
     * 
     * @type {number}
     * @memberof AgentUpdate
     */
    indexId?: number | null;
    /**
     * 
     * @type {string}
     * @memberof AgentUpdate
     */
    modelName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AgentUpdate
     */
    name?: string | null;
}

/**
 * Check if a given object implements the AgentUpdate interface.
 */
export function instanceOfAgentUpdate(value: object): value is AgentUpdate {
    return true;
}

export function AgentUpdateFromJSON(json: any): AgentUpdate {
    return AgentUpdateFromJSONTyped(json, false);
}

export function AgentUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): AgentUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'] == null ? undefined : json['description'],
        'indexId': json['index_id'] == null ? undefined : json['index_id'],
        'modelName': json['model_name'] == null ? undefined : json['model_name'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function AgentUpdateToJSON(json: any): AgentUpdate {
    return AgentUpdateToJSONTyped(json, false);
}

export function AgentUpdateToJSONTyped(value?: AgentUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
        'index_id': value['indexId'],
        'model_name': value['modelName'],
        'name': value['name'],
    };
}

