/* tslint:disable */
/* eslint-disable */
/**
 * RAG API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AgentInfo
 */
export interface AgentInfo {
    /**
     * 
     * @type {string}
     * @memberof AgentInfo
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AgentInfo
     */
    description?: string | null;
    /**
     * 
     * @type {number}
     * @memberof AgentInfo
     */
    indexId?: number | null;
    /**
     * 
     * @type {string}
     * @memberof AgentInfo
     */
    modelName?: string | null;
}

/**
 * Check if a given object implements the AgentInfo interface.
 */
export function instanceOfAgentInfo(value: object): value is AgentInfo {
    return true;
}

export function AgentInfoFromJSON(json: any): AgentInfo {
    return AgentInfoFromJSONTyped(json, false);
}

export function AgentInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AgentInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'indexId': json['index_id'] == null ? undefined : json['index_id'],
        'modelName': json['model_name'] == null ? undefined : json['model_name'],
    };
}

export function AgentInfoToJSON(json: any): AgentInfo {
    return AgentInfoToJSONTyped(json, false);
}

export function AgentInfoToJSONTyped(value?: AgentInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'index_id': value['indexId'],
        'model_name': value['modelName'],
    };
}

