/* tslint:disable */
/* eslint-disable */
/**
 * RAG API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiSchemasChatConversationInfo
 */
export interface ApiSchemasChatConversationInfo {
    /**
     * List of messages in the conversation as (human, agent) tuples
     * @type {Array<Array<any>>}
     * @memberof ApiSchemasChatConversationInfo
     */
    messages: Array<Array<any>>;
    /**
     * List of chat suggestions for the user
     * @type {Array<Array<string>>}
     * @memberof ApiSchemasChatConversationInfo
     */
    chatSuggestions: Array<Array<string>>;
    /**
     * List of retrieval messages used in the conversation
     * @type {Array<string>}
     * @memberof ApiSchemasChatConversationInfo
     */
    retrievalMessages: Array<string>;
    /**
     * History of plots generated during the conversation
     * @type {Array<any>}
     * @memberof ApiSchemasChatConversationInfo
     */
    plotHistory: Array<any>;
    /**
     * List of files selected for the conversation
     * @type {{ [key: string]: any; }}
     * @memberof ApiSchemasChatConversationInfo
     */
    selected: { [key: string]: any; };
    /**
     * State information for the conversation
     * @type {{ [key: string]: any; }}
     * @memberof ApiSchemasChatConversationInfo
     */
    state: { [key: string]: any; };
    /**
     * List of likes/dislikes for messages in the conversation
     * @type {Array<any>}
     * @memberof ApiSchemasChatConversationInfo
     */
    likes: Array<any>;
}

/**
 * Check if a given object implements the ApiSchemasChatConversationInfo interface.
 */
export function instanceOfApiSchemasChatConversationInfo(value: object): value is ApiSchemasChatConversationInfo {
    if (!('messages' in value) || value['messages'] === undefined) return false;
    if (!('chatSuggestions' in value) || value['chatSuggestions'] === undefined) return false;
    if (!('retrievalMessages' in value) || value['retrievalMessages'] === undefined) return false;
    if (!('plotHistory' in value) || value['plotHistory'] === undefined) return false;
    if (!('selected' in value) || value['selected'] === undefined) return false;
    if (!('state' in value) || value['state'] === undefined) return false;
    if (!('likes' in value) || value['likes'] === undefined) return false;
    return true;
}

export function ApiSchemasChatConversationInfoFromJSON(json: any): ApiSchemasChatConversationInfo {
    return ApiSchemasChatConversationInfoFromJSONTyped(json, false);
}

export function ApiSchemasChatConversationInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiSchemasChatConversationInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'messages': json['messages'],
        'chatSuggestions': json['chat_suggestions'],
        'retrievalMessages': json['retrieval_messages'],
        'plotHistory': json['plot_history'],
        'selected': json['selected'],
        'state': json['state'],
        'likes': json['likes'],
    };
}

export function ApiSchemasChatConversationInfoToJSON(json: any): ApiSchemasChatConversationInfo {
    return ApiSchemasChatConversationInfoToJSONTyped(json, false);
}

export function ApiSchemasChatConversationInfoToJSONTyped(value?: ApiSchemasChatConversationInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'messages': value['messages'],
        'chat_suggestions': value['chatSuggestions'],
        'retrieval_messages': value['retrievalMessages'],
        'plot_history': value['plotHistory'],
        'selected': value['selected'],
        'state': value['state'],
        'likes': value['likes'],
    };
}

