/* tslint:disable */
/* eslint-disable */
/**
 * RAG API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiSchemasConversationsConversationInfo
 */
export interface ApiSchemasConversationsConversationInfo {
    /**
     * The ID of the conversation
     * @type {string}
     * @memberof ApiSchemasConversationsConversationInfo
     */
    id: string;
    /**
     * The name of the conversation
     * @type {string}
     * @memberof ApiSchemasConversationsConversationInfo
     */
    name: string;
    /**
     * The ID of the user who owns the conversation
     * @type {string}
     * @memberof ApiSchemasConversationsConversationInfo
     */
    user: string;
    /**
     * Whether the conversation is public
     * @type {boolean}
     * @memberof ApiSchemasConversationsConversationInfo
     */
    isPublic?: boolean;
    /**
     * The creation timestamp of the conversation
     * @type {Date}
     * @memberof ApiSchemasConversationsConversationInfo
     */
    dateCreated: Date;
    /**
     * The last update timestamp of the conversation
     * @type {Date}
     * @memberof ApiSchemasConversationsConversationInfo
     */
    dateUpdated: Date;
    /**
     * 
     * @type {string}
     * @memberof ApiSchemasConversationsConversationInfo
     */
    agentId?: string | null;
}

/**
 * Check if a given object implements the ApiSchemasConversationsConversationInfo interface.
 */
export function instanceOfApiSchemasConversationsConversationInfo(value: object): value is ApiSchemasConversationsConversationInfo {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('user' in value) || value['user'] === undefined) return false;
    if (!('dateCreated' in value) || value['dateCreated'] === undefined) return false;
    if (!('dateUpdated' in value) || value['dateUpdated'] === undefined) return false;
    return true;
}

export function ApiSchemasConversationsConversationInfoFromJSON(json: any): ApiSchemasConversationsConversationInfo {
    return ApiSchemasConversationsConversationInfoFromJSONTyped(json, false);
}

export function ApiSchemasConversationsConversationInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiSchemasConversationsConversationInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'user': json['user'],
        'isPublic': json['is_public'] == null ? undefined : json['is_public'],
        'dateCreated': (new Date(json['date_created'])),
        'dateUpdated': (new Date(json['date_updated'])),
        'agentId': json['agent_id'] == null ? undefined : json['agent_id'],
    };
}

export function ApiSchemasConversationsConversationInfoToJSON(json: any): ApiSchemasConversationsConversationInfo {
    return ApiSchemasConversationsConversationInfoToJSONTyped(json, false);
}

export function ApiSchemasConversationsConversationInfoToJSONTyped(value?: ApiSchemasConversationsConversationInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'user': value['user'],
        'is_public': value['isPublic'],
        'date_created': value['dateCreated'].toISOString(),
        'date_updated': value['dateUpdated'].toISOString(),
        'agent_id': value['agentId'],
    };
}

