/* tslint:disable */
/* eslint-disable */
/**
 * RAG API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BodyUpdateGroupApiV1IndexIndexIdGroupsGroupIdPatch
 */
export interface BodyUpdateGroupApiV1IndexIndexIdGroupsGroupIdPatch {
    /**
     * 
     * @type {Array<string>}
     * @memberof BodyUpdateGroupApiV1IndexIndexIdGroupsGroupIdPatch
     */
    fileIds?: Array<string> | null;
}

/**
 * Check if a given object implements the BodyUpdateGroupApiV1IndexIndexIdGroupsGroupIdPatch interface.
 */
export function instanceOfBodyUpdateGroupApiV1IndexIndexIdGroupsGroupIdPatch(value: object): value is BodyUpdateGroupApiV1IndexIndexIdGroupsGroupIdPatch {
    return true;
}

export function BodyUpdateGroupApiV1IndexIndexIdGroupsGroupIdPatchFromJSON(json: any): BodyUpdateGroupApiV1IndexIndexIdGroupsGroupIdPatch {
    return BodyUpdateGroupApiV1IndexIndexIdGroupsGroupIdPatchFromJSONTyped(json, false);
}

export function BodyUpdateGroupApiV1IndexIndexIdGroupsGroupIdPatchFromJSONTyped(json: any, ignoreDiscriminator: boolean): BodyUpdateGroupApiV1IndexIndexIdGroupsGroupIdPatch {
    if (json == null) {
        return json;
    }
    return {
        
        'fileIds': json['file_ids'] == null ? undefined : json['file_ids'],
    };
}

export function BodyUpdateGroupApiV1IndexIndexIdGroupsGroupIdPatchToJSON(json: any): BodyUpdateGroupApiV1IndexIndexIdGroupsGroupIdPatch {
    return BodyUpdateGroupApiV1IndexIndexIdGroupsGroupIdPatchToJSONTyped(json, false);
}

export function BodyUpdateGroupApiV1IndexIndexIdGroupsGroupIdPatchToJSONTyped(value?: BodyUpdateGroupApiV1IndexIndexIdGroupsGroupIdPatch | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'file_ids': value['fileIds'],
    };
}

