/* tslint:disable */
/* eslint-disable */
/**
 * RAG API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BodyUpdateAgentUsersAndCreatorsApiV1AgentsAgentIdUsersPost
 */
export interface BodyUpdateAgentUsersAndCreatorsApiV1AgentsAgentIdUsersPost {
    /**
     * 
     * @type {Array<string>}
     * @memberof BodyUpdateAgentUsersAndCreatorsApiV1AgentsAgentIdUsersPost
     */
    users: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof BodyUpdateAgentUsersAndCreatorsApiV1AgentsAgentIdUsersPost
     */
    creators: Array<string>;
}

/**
 * Check if a given object implements the BodyUpdateAgentUsersAndCreatorsApiV1AgentsAgentIdUsersPost interface.
 */
export function instanceOfBodyUpdateAgentUsersAndCreatorsApiV1AgentsAgentIdUsersPost(value: object): value is BodyUpdateAgentUsersAndCreatorsApiV1AgentsAgentIdUsersPost {
    if (!('users' in value) || value['users'] === undefined) return false;
    if (!('creators' in value) || value['creators'] === undefined) return false;
    return true;
}

export function BodyUpdateAgentUsersAndCreatorsApiV1AgentsAgentIdUsersPostFromJSON(json: any): BodyUpdateAgentUsersAndCreatorsApiV1AgentsAgentIdUsersPost {
    return BodyUpdateAgentUsersAndCreatorsApiV1AgentsAgentIdUsersPostFromJSONTyped(json, false);
}

export function BodyUpdateAgentUsersAndCreatorsApiV1AgentsAgentIdUsersPostFromJSONTyped(json: any, ignoreDiscriminator: boolean): BodyUpdateAgentUsersAndCreatorsApiV1AgentsAgentIdUsersPost {
    if (json == null) {
        return json;
    }
    return {
        
        'users': json['users'],
        'creators': json['creators'],
    };
}

export function BodyUpdateAgentUsersAndCreatorsApiV1AgentsAgentIdUsersPostToJSON(json: any): BodyUpdateAgentUsersAndCreatorsApiV1AgentsAgentIdUsersPost {
    return BodyUpdateAgentUsersAndCreatorsApiV1AgentsAgentIdUsersPostToJSONTyped(json, false);
}

export function BodyUpdateAgentUsersAndCreatorsApiV1AgentsAgentIdUsersPostToJSONTyped(value?: BodyUpdateAgentUsersAndCreatorsApiV1AgentsAgentIdUsersPost | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'users': value['users'],
        'creators': value['creators'],
    };
}

