/* tslint:disable */
/* eslint-disable */
/**
 * RAG API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChatRequest
 */
export interface ChatRequest {
    /**
     * Message to send
     * @type {string}
     * @memberof ChatRequest
     */
    message: string;
    /**
     * 
     * @type {string}
     * @memberof ChatRequest
     */
    reasoningType?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ChatRequest
     */
    llmType?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof ChatRequest
     */
    useMindMap?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof ChatRequest
     */
    useCitation?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof ChatRequest
     */
    language?: string | null;
}

/**
 * Check if a given object implements the ChatRequest interface.
 */
export function instanceOfChatRequest(value: object): value is ChatRequest {
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function ChatRequestFromJSON(json: any): ChatRequest {
    return ChatRequestFromJSONTyped(json, false);
}

export function ChatRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
        'reasoningType': json['reasoning_type'] == null ? undefined : json['reasoning_type'],
        'llmType': json['llm_type'] == null ? undefined : json['llm_type'],
        'useMindMap': json['use_mind_map'] == null ? undefined : json['use_mind_map'],
        'useCitation': json['use_citation'] == null ? undefined : json['use_citation'],
        'language': json['language'] == null ? undefined : json['language'],
    };
}

export function ChatRequestToJSON(json: any): ChatRequest {
    return ChatRequestToJSONTyped(json, false);
}

export function ChatRequestToJSONTyped(value?: ChatRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'reasoning_type': value['reasoningType'],
        'llm_type': value['llmType'],
        'use_mind_map': value['useMindMap'],
        'use_citation': value['useCitation'],
        'language': value['language'],
    };
}

