/* tslint:disable */
/* eslint-disable */
/**
 * RAG API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConversationUpdate
 */
export interface ConversationUpdate {
    /**
     * 
     * @type {string}
     * @memberof ConversationUpdate
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ConversationUpdate
     */
    user?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof ConversationUpdate
     */
    isPublic?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof ConversationUpdate
     */
    agentId?: string | null;
}

/**
 * Check if a given object implements the ConversationUpdate interface.
 */
export function instanceOfConversationUpdate(value: object): value is ConversationUpdate {
    return true;
}

export function ConversationUpdateFromJSON(json: any): ConversationUpdate {
    return ConversationUpdateFromJSONTyped(json, false);
}

export function ConversationUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConversationUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'user': json['user'] == null ? undefined : json['user'],
        'isPublic': json['is_public'] == null ? undefined : json['is_public'],
        'agentId': json['agent_id'] == null ? undefined : json['agent_id'],
    };
}

export function ConversationUpdateToJSON(json: any): ConversationUpdate {
    return ConversationUpdateToJSONTyped(json, false);
}

export function ConversationUpdateToJSONTyped(value?: ConversationUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'user': value['user'],
        'is_public': value['isPublic'],
        'agent_id': value['agentId'],
    };
}

