/* tslint:disable */
/* eslint-disable */
/**
 * RAG API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConversationCreate
 */
export interface ConversationCreate {
    /**
     * The name of the conversation
     * @type {string}
     * @memberof ConversationCreate
     */
    name: string;
    /**
     * Whether the conversation is public
     * @type {boolean}
     * @memberof ConversationCreate
     */
    isPublic?: boolean;
    /**
     * The ID of the agent associated with the conversation
     * @type {string}
     * @memberof ConversationCreate
     */
    agentId: string;
}

/**
 * Check if a given object implements the ConversationCreate interface.
 */
export function instanceOfConversationCreate(value: object): value is ConversationCreate {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('agentId' in value) || value['agentId'] === undefined) return false;
    return true;
}

export function ConversationCreateFromJSON(json: any): ConversationCreate {
    return ConversationCreateFromJSONTyped(json, false);
}

export function ConversationCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConversationCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'isPublic': json['is_public'] == null ? undefined : json['is_public'],
        'agentId': json['agent_id'],
    };
}

export function ConversationCreateToJSON(json: any): ConversationCreate {
    return ConversationCreateToJSONTyped(json, false);
}

export function ConversationCreateToJSONTyped(value?: ConversationCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'is_public': value['isPublic'],
        'agent_id': value['agentId'],
    };
}

