/* tslint:disable */
/* eslint-disable */
/**
 * RAG API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EmbeddingCreate
 */
export interface EmbeddingCreate {
    /**
     * The name of the embedding model
     * @type {string}
     * @memberof EmbeddingCreate
     */
    name: string;
    /**
     * The specification of the embedding model
     * @type {{ [key: string]: any; }}
     * @memberof EmbeddingCreate
     */
    spec: { [key: string]: any; };
    /**
     * Whether this embedding model is the default one
     * @type {boolean}
     * @memberof EmbeddingCreate
     */
    _default?: boolean;
    /**
     * The vendor of the embedding model
     * @type {string}
     * @memberof EmbeddingCreate
     */
    vendorName: string;
}

/**
 * Check if a given object implements the EmbeddingCreate interface.
 */
export function instanceOfEmbeddingCreate(value: object): value is EmbeddingCreate {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('spec' in value) || value['spec'] === undefined) return false;
    if (!('vendorName' in value) || value['vendorName'] === undefined) return false;
    return true;
}

export function EmbeddingCreateFromJSON(json: any): EmbeddingCreate {
    return EmbeddingCreateFromJSONTyped(json, false);
}

export function EmbeddingCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmbeddingCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'spec': json['spec'],
        '_default': json['default'] == null ? undefined : json['default'],
        'vendorName': json['vendor_name'],
    };
}

export function EmbeddingCreateToJSON(json: any): EmbeddingCreate {
    return EmbeddingCreateToJSONTyped(json, false);
}

export function EmbeddingCreateToJSONTyped(value?: EmbeddingCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'spec': value['spec'],
        'default': value['_default'],
        'vendor_name': value['vendorName'],
    };
}

