/* tslint:disable */
/* eslint-disable */
/**
 * RAG API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EmbeddingInfo
 */
export interface EmbeddingInfo {
    /**
     * The name of the embedding model
     * @type {string}
     * @memberof EmbeddingInfo
     */
    name: string;
    /**
     * The specification of the embedding model
     * @type {object}
     * @memberof EmbeddingInfo
     */
    spec: object;
    /**
     * Whether this embedding model is the default one
     * @type {boolean}
     * @memberof EmbeddingInfo
     */
    _default?: boolean;
    /**
     * The vendor of the embedding model
     * @type {string}
     * @memberof EmbeddingInfo
     */
    vendorName: string;
    /**
     * The qualified name of the vendor
     * @type {string}
     * @memberof EmbeddingInfo
     */
    vendorQualname: string;
}

/**
 * Check if a given object implements the EmbeddingInfo interface.
 */
export function instanceOfEmbeddingInfo(value: object): value is EmbeddingInfo {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('spec' in value) || value['spec'] === undefined) return false;
    if (!('vendorName' in value) || value['vendorName'] === undefined) return false;
    if (!('vendorQualname' in value) || value['vendorQualname'] === undefined) return false;
    return true;
}

export function EmbeddingInfoFromJSON(json: any): EmbeddingInfo {
    return EmbeddingInfoFromJSONTyped(json, false);
}

export function EmbeddingInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmbeddingInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'spec': json['spec'],
        '_default': json['default'] == null ? undefined : json['default'],
        'vendorName': json['vendor_name'],
        'vendorQualname': json['vendor_qualname'],
    };
}

export function EmbeddingInfoToJSON(json: any): EmbeddingInfo {
    return EmbeddingInfoToJSONTyped(json, false);
}

export function EmbeddingInfoToJSONTyped(value?: EmbeddingInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'spec': value['spec'],
        'default': value['_default'],
        'vendor_name': value['vendorName'],
        'vendor_qualname': value['vendorQualname'],
    };
}

