/* tslint:disable */
/* eslint-disable */
/**
 * RAG API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FileInfo
 */
export interface FileInfo {
    /**
     * The unique identifier of the file
     * @type {string}
     * @memberof FileInfo
     */
    id: string;
    /**
     * The name of the file
     * @type {string}
     * @memberof FileInfo
     */
    name: string;
    /**
     * The size of the file
     * @type {string}
     * @memberof FileInfo
     */
    size: string;
    /**
     * The number of tokens in the file
     * @type {string}
     * @memberof FileInfo
     */
    tokens: string;
    /**
     * The loader used for the file
     * @type {string}
     * @memberof FileInfo
     */
    loader: string;
    /**
     * The creation timestamp of the file
     * @type {string}
     * @memberof FileInfo
     */
    dateCreated: string;
}

/**
 * Check if a given object implements the FileInfo interface.
 */
export function instanceOfFileInfo(value: object): value is FileInfo {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('size' in value) || value['size'] === undefined) return false;
    if (!('tokens' in value) || value['tokens'] === undefined) return false;
    if (!('loader' in value) || value['loader'] === undefined) return false;
    if (!('dateCreated' in value) || value['dateCreated'] === undefined) return false;
    return true;
}

export function FileInfoFromJSON(json: any): FileInfo {
    return FileInfoFromJSONTyped(json, false);
}

export function FileInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): FileInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'size': json['size'],
        'tokens': json['tokens'],
        'loader': json['loader'],
        'dateCreated': json['date_created'],
    };
}

export function FileInfoToJSON(json: any): FileInfo {
    return FileInfoToJSONTyped(json, false);
}

export function FileInfoToJSONTyped(value?: FileInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'size': value['size'],
        'tokens': value['tokens'],
        'loader': value['loader'],
        'date_created': value['dateCreated'],
    };
}

