/* tslint:disable */
/* eslint-disable */
/**
 * RAG API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GenericException
 */
export interface GenericException {
    /**
     * A description of the error
     * @type {string}
     * @memberof GenericException
     */
    detail: string;
}

/**
 * Check if a given object implements the GenericException interface.
 */
export function instanceOfGenericException(value: object): value is GenericException {
    if (!('detail' in value) || value['detail'] === undefined) return false;
    return true;
}

export function GenericExceptionFromJSON(json: any): GenericException {
    return GenericExceptionFromJSONTyped(json, false);
}

export function GenericExceptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): GenericException {
    if (json == null) {
        return json;
    }
    return {
        
        'detail': json['detail'],
    };
}

export function GenericExceptionToJSON(json: any): GenericException {
    return GenericExceptionToJSONTyped(json, false);
}

export function GenericExceptionToJSONTyped(value?: GenericException | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'detail': value['detail'],
    };
}

