/* tslint:disable */
/* eslint-disable */
/**
 * RAG API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GroupInfo
 */
export interface GroupInfo {
    /**
     * The unique identifier of the group
     * @type {string}
     * @memberof GroupInfo
     */
    id: string;
    /**
     * The name of the group
     * @type {string}
     * @memberof GroupInfo
     */
    name: string;
    /**
     * List of file IDs in the group
     * @type {Array<string>}
     * @memberof GroupInfo
     */
    files: Array<string>;
    /**
     * The creation timestamp of the group
     * @type {string}
     * @memberof GroupInfo
     */
    dateCreated: string;
}

/**
 * Check if a given object implements the GroupInfo interface.
 */
export function instanceOfGroupInfo(value: object): value is GroupInfo {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('files' in value) || value['files'] === undefined) return false;
    if (!('dateCreated' in value) || value['dateCreated'] === undefined) return false;
    return true;
}

export function GroupInfoFromJSON(json: any): GroupInfo {
    return GroupInfoFromJSONTyped(json, false);
}

export function GroupInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GroupInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'files': json['files'],
        'dateCreated': json['date_created'],
    };
}

export function GroupInfoToJSON(json: any): GroupInfo {
    return GroupInfoToJSONTyped(json, false);
}

export function GroupInfoToJSONTyped(value?: GroupInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'files': value['files'],
        'date_created': value['dateCreated'],
    };
}

