/* tslint:disable */
/* eslint-disable */
/**
 * RAG API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IndexInfo
 */
export interface IndexInfo {
    /**
     * The name of the index
     * @type {string}
     * @memberof IndexInfo
     */
    name: string;
    /**
     * The type of the index
     * @type {string}
     * @memberof IndexInfo
     */
    indexType: string;
    /**
     * The configuration of the index
     * @type {object}
     * @memberof IndexInfo
     */
    config: object;
    /**
     * The unique identifier of the index
     * @type {string}
     * @memberof IndexInfo
     */
    id: string;
}

/**
 * Check if a given object implements the IndexInfo interface.
 */
export function instanceOfIndexInfo(value: object): value is IndexInfo {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('indexType' in value) || value['indexType'] === undefined) return false;
    if (!('config' in value) || value['config'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function IndexInfoFromJSON(json: any): IndexInfo {
    return IndexInfoFromJSONTyped(json, false);
}

export function IndexInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): IndexInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'indexType': json['index_type'],
        'config': json['config'],
        'id': json['id'],
    };
}

export function IndexInfoToJSON(json: any): IndexInfo {
    return IndexInfoToJSONTyped(json, false);
}

export function IndexInfoToJSONTyped(value?: IndexInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'index_type': value['indexType'],
        'config': value['config'],
        'id': value['id'],
    };
}

