/* tslint:disable */
/* eslint-disable */
/**
 * RAG API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Liked
 */
export interface Liked {
}

/**
 * Check if a given object implements the Liked interface.
 */
export function instanceOfLiked(value: object): value is Liked {
    return true;
}

export function LikedFromJSON(json: any): Liked {
    return LikedFromJSONTyped(json, false);
}

export function LikedFromJSONTyped(json: any, ignoreDiscriminator: boolean): Liked {
    return json;
}

export function LikedToJSON(json: any): Liked {
    return LikedToJSONTyped(json, false);
}

export function LikedToJSONTyped(value?: Liked | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

