/* tslint:disable */
/* eslint-disable */
/**
 * RAG API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LlmCreate
 */
export interface LlmCreate {
    /**
     * The name of the LLM
     * @type {string}
     * @memberof LlmCreate
     */
    name: string;
    /**
     * The specification of the LLM
     * @type {object}
     * @memberof LlmCreate
     */
    spec: object;
    /**
     * Whether this LLM is the default one
     * @type {boolean}
     * @memberof LlmCreate
     */
    _default?: boolean;
    /**
     * The vendor of the LLM
     * @type {string}
     * @memberof LlmCreate
     */
    vendorName: string;
}

/**
 * Check if a given object implements the LlmCreate interface.
 */
export function instanceOfLlmCreate(value: object): value is LlmCreate {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('spec' in value) || value['spec'] === undefined) return false;
    if (!('vendorName' in value) || value['vendorName'] === undefined) return false;
    return true;
}

export function LlmCreateFromJSON(json: any): LlmCreate {
    return LlmCreateFromJSONTyped(json, false);
}

export function LlmCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): LlmCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'spec': json['spec'],
        '_default': json['default'] == null ? undefined : json['default'],
        'vendorName': json['vendor_name'],
    };
}

export function LlmCreateToJSON(json: any): LlmCreate {
    return LlmCreateToJSONTyped(json, false);
}

export function LlmCreateToJSONTyped(value?: LlmCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'spec': value['spec'],
        'default': value['_default'],
        'vendor_name': value['vendorName'],
    };
}

