/* tslint:disable */
/* eslint-disable */
/**
 * RAG API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RerankingInfo
 */
export interface RerankingInfo {
    /**
     * The name of the reranking model
     * @type {string}
     * @memberof RerankingInfo
     */
    name: string;
    /**
     * The specification of the reranking model
     * @type {{ [key: string]: any; }}
     * @memberof RerankingInfo
     */
    spec: { [key: string]: any; };
    /**
     * Whether this reranking model is the default one
     * @type {boolean}
     * @memberof RerankingInfo
     */
    _default?: boolean;
    /**
     * The vendor of the reranking model
     * @type {string}
     * @memberof RerankingInfo
     */
    vendorName: string;
    /**
     * The qualified name of the vendor
     * @type {string}
     * @memberof RerankingInfo
     */
    vendorQualname: string;
}

/**
 * Check if a given object implements the RerankingInfo interface.
 */
export function instanceOfRerankingInfo(value: object): value is RerankingInfo {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('spec' in value) || value['spec'] === undefined) return false;
    if (!('vendorName' in value) || value['vendorName'] === undefined) return false;
    if (!('vendorQualname' in value) || value['vendorQualname'] === undefined) return false;
    return true;
}

export function RerankingInfoFromJSON(json: any): RerankingInfo {
    return RerankingInfoFromJSONTyped(json, false);
}

export function RerankingInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RerankingInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'spec': json['spec'],
        '_default': json['default'] == null ? undefined : json['default'],
        'vendorName': json['vendor_name'],
        'vendorQualname': json['vendor_qualname'],
    };
}

export function RerankingInfoToJSON(json: any): RerankingInfo {
    return RerankingInfoToJSONTyped(json, false);
}

export function RerankingInfoToJSONTyped(value?: RerankingInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'spec': value['spec'],
        'default': value['_default'],
        'vendor_name': value['vendorName'],
        'vendor_qualname': value['vendorQualname'],
    };
}

