/* tslint:disable */
/* eslint-disable */
/**
 * RAG API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RerankingCreate
 */
export interface RerankingCreate {
    /**
     * The name of the reranking model
     * @type {string}
     * @memberof RerankingCreate
     */
    name: string;
    /**
     * The specification of the reranking model
     * @type {{ [key: string]: string; }}
     * @memberof RerankingCreate
     */
    spec: { [key: string]: string; };
    /**
     * Whether this reranking model is the default one
     * @type {boolean}
     * @memberof RerankingCreate
     */
    _default?: boolean;
    /**
     * The vendor of the reranking model
     * @type {string}
     * @memberof RerankingCreate
     */
    vendorName: string;
}

/**
 * Check if a given object implements the RerankingCreate interface.
 */
export function instanceOfRerankingCreate(value: object): value is RerankingCreate {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('spec' in value) || value['spec'] === undefined) return false;
    if (!('vendorName' in value) || value['vendorName'] === undefined) return false;
    return true;
}

export function RerankingCreateFromJSON(json: any): RerankingCreate {
    return RerankingCreateFromJSONTyped(json, false);
}

export function RerankingCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): RerankingCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'spec': json['spec'],
        '_default': json['default'] == null ? undefined : json['default'],
        'vendorName': json['vendor_name'],
    };
}

export function RerankingCreateToJSON(json: any): RerankingCreate {
    return RerankingCreateToJSONTyped(json, false);
}

export function RerankingCreateToJSONTyped(value?: RerankingCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'spec': value['spec'],
        'default': value['_default'],
        'vendor_name': value['vendorName'],
    };
}

