/* tslint:disable */
/* eslint-disable */
/**
 * RAG API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const SelectMode = {
    All: 'all',
    Select: 'select',
    Disabled: 'disabled'
} as const;
export type SelectMode = typeof SelectMode[keyof typeof SelectMode];


export function instanceOfSelectMode(value: any): boolean {
    for (const key in SelectMode) {
        if (Object.prototype.hasOwnProperty.call(SelectMode, key)) {
            if (SelectMode[key as keyof typeof SelectMode] === value) {
                return true;
            }
        }
    }
    return false;
}

export function SelectModeFromJSON(json: any): SelectMode {
    return SelectModeFromJSONTyped(json, false);
}

export function SelectModeFromJSONTyped(json: any, ignoreDiscriminator: boolean): SelectMode {
    return json as SelectMode;
}

export function SelectModeToJSON(value?: SelectMode | null): any {
    return value as any;
}

export function SelectModeToJSONTyped(value: any, ignoreDiscriminator: boolean): SelectMode {
    return value as SelectMode;
}

